#include "stitchCommand.cxx"
#include "stitchCommandReader.cxx"
#include "stitchCylindricalLens.cxx"
#include "stitchFile.cxx"
#include "stitchFisheyeLens.cxx"
#include "stitchImage.cxx"
#include "stitchImageCommandOutput.cxx"
#include "stitchImageRasterizer.cxx"
#include "stitchLens.cxx"
#include "stitchPSphereLens.cxx"
#include "stitchPerspectiveLens.cxx"
#include "stitchPoint.cxx"
#include "stitcher.cxx"
#include "stitchCylindricalScreen.cxx"
#include "stitchFlatScreen.cxx"
#include "stitchMultiScreen.cxx"
#include "stitchScreen.cxx"

