#include "config_pnmimagetypes.cxx"
#include "pnmFileTypeBMPReader.cxx"
#include "pnmFileTypeBMPWriter.cxx"
#include "pnmFileTypeIMG.cxx"
#include "pnmFileTypeBMP.cxx"
#include "pnmFileTypeJPG.cxx"
#include "pnmFileTypeJPGReader.cxx"
#include "pnmFileTypeJPGWriter.cxx"
