#include "pnmFileTypePNG.cxx"
#include "pnmFileTypeTIFF.cxx"
#include "pnmFileTypePNM.cxx"
#include "pnmFileTypePfm.cxx"
#include "pnmFileTypeSGI.cxx"
#include "pnmFileTypeSGIReader.cxx"
#include "pnmFileTypeSGIWriter.cxx"
#include "pnmFileTypeSoftImage.cxx"
#include "pnmFileTypeStbImage.cxx"
#include "pnmFileTypeTGA.cxx"

