// Filename: glesext_shadow.h
// Created by:  drose (09Apr09)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) Carnegie Mellon University.  All rights reserved.
//
// All use of this software is subject to the terms of the revised BSD
// license.  You should have received a copy of this license along
// with this source code in a file named "LICENSE."
//
////////////////////////////////////////////////////////////////////

// This file is designed to #define the extension symbols that aren't
// used for OpenGL ES, just so we can compile the glstuff module.
// These symbols have to be defined, even if they are never actually
// used at runtime; and it doesn't particularly matter what their
// defined value is.

#define GL_ACCUM_ALPHA_BITS 0
#define GL_ACCUM_BLUE_BITS 1
#define GL_ACCUM_BUFFER_BIT 2
#define GL_ACCUM_GREEN_BITS 3
#define GL_ACCUM_RED_BITS 4
#define GL_AUX_BUFFERS 5
#define GL_BACK_LEFT 6
#define GL_BACK_RIGHT 7
#define GL_BGR 8
#define GL_BLUE 9
#define GL_CLAMP 10
#define GL_CLAMP_TO_BORDER 11
#define GL_COLOR_ATTACHMENT0_EXT 12
#define GL_COLOR_ATTACHMENT1_EXT 13
#define GL_COLOR_INDEX 14
#define GL_COMPARE_R_TO_TEXTURE_ARB 15
#define GL_COMPILE 16
#define GL_COMPILE_AND_EXECUTE 17
#define GL_COMPRESSED_ALPHA 18
#define GL_COMPRESSED_LUMINANCE 19
#define GL_COMPRESSED_LUMINANCE_ALPHA 20
#define GL_COMPRESSED_RGB 21
#define GL_COMPRESSED_RGBA 22
#define GL_COMPRESSED_RGBA_FXT1_3DFX 23
#define GL_COMPRESSED_RGBA_S3TC_DXT1_EXT 24
#define GL_COMPRESSED_RGBA_S3TC_DXT3_EXT 25
#define GL_COMPRESSED_RGBA_S3TC_DXT5_EXT 26
#define GL_COMPRESSED_RGB_FXT1_3DFX 27
#define GL_COMPRESSED_RGB_S3TC_DXT1_EXT 28
#define GL_CONSTANT_ALPHA 29
#define GL_CONSTANT_COLOR 30
#define GL_COORD_REPLACE_ARB 31
#define GL_DECR_WRAP 32
#define GL_DEPTH_ATTACHMENT_EXT 33
#define GL_DEPTH_COMPONENT 34
#define GL_DEPTH_STENCIL_EXT 35
#define GL_DEPTH_TEXTURE_MODE_ARB 36
#define GL_DOUBLEBUFFER 37
#define GL_EYE_LINEAR 38
#define GL_EYE_PLANE 39
#define GL_FILL 40
#define GL_FRAMEBUFFER_COMPLETE_EXT 41
#define GL_FRAMEBUFFER_EXT 42
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT 43
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT 44
#define GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT 45
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT 46
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT 47
#define GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT 48
#define GL_FRAMEBUFFER_UNSUPPORTED_EXT 49
#define GL_FRONT_LEFT 50
#define GL_FRONT_RIGHT 51
#define GL_FUNC_ADD 52
#define GL_FUNC_REVERSE_SUBTRACT 53
#define GL_FUNC_SUBTRACT 54
#define GL_GREEN 55
#define GL_INCR_WRAP 56
#define GL_INDEX_BITS 57
#define GL_INTENSITY 58
#define GL_LEFT 59
#define GL_LIGHT_MODEL_LOCAL_VIEWER 60
#define GL_LINE 61
#define GL_MATRIX_INDEX_ARRAY_ARB 62
#define GL_MATRIX_PALETTE_ARB 63
#define GL_MAX 64
#define GL_MAX_3D_TEXTURE_SIZE 65
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE 66
#define GL_MAX_DRAW_BUFFERS 67
#define GL_MAX_ELEMENTS_INDICES 68
#define GL_MAX_ELEMENTS_VERTICES 69
#define GL_MAX_PALETTE_MATRICES_ARB 70
#define GL_MAX_VERTEX_UNITS_ARB 71
#define GL_MIN 72
#define GL_MIRRORED_REPEAT 73
#define GL_MIRROR_CLAMP_EXT 74
#define GL_MIRROR_CLAMP_TO_BORDER_EXT 75
#define GL_MIRROR_CLAMP_TO_EDGE_EXT 76
#define GL_MODELVIEW0_ARB 77
#define GL_MODELVIEW1_ARB 78
#define GL_MODELVIEW2_ARB 79
#define GL_NONE 80
#define GL_NORMAL_MAP 81
#define GL_OBJECT_LINEAR 82
#define GL_OBJECT_PLANE 83
#define GL_ONE_MINUS_CONSTANT_ALPHA 84
#define GL_ONE_MINUS_CONSTANT_COLOR 85
#define GL_POINT 86
#define GL_POINT_SPRITE_ARB 87
#define GL_POLYGON_SMOOTH 88
#define GL_POLYGON_SMOOTH_HINT 89
#define GL_Q 90
#define GL_QUERY_COUNTER_BITS 91
#define GL_R 92
#define GL_R3_G3_B2 93
#define GL_RED 94
#define GL_REFLECTION_MAP 95
#define GL_RENDERBUFFER_EXT 96
#define GL_RGB12 97
#define GL_RGB5 98
#define GL_RGB5_A1 99
#define GL_RGB8 100
#define GL_RGBA12 101
#define GL_RGBA16F_ARB 102
#define GL_RGBA32F_ARB 103
#define GL_RGBA4 104
#define GL_RGBA8 105
#define GL_RGBA8_EXT 106
#define GL_RIGHT 107
#define GL_S 108
#define GL_SAMPLES_PASSED 109
#define GL_SPHERE_MAP 110
#define GL_STENCIL_ATTACHMENT_EXT 111
#define GL_STENCIL_TEST_TWO_SIDE_EXT 112
#define GL_STEREO 113
#define GL_STREAM_DRAW 114
#define GL_T 115
#define GL_TEXTURE_1D 116
#define GL_TEXTURE_3D 117
#define GL_TEXTURE_ALPHA_SIZE 118
#define GL_TEXTURE_BLUE_SIZE 119
#define GL_TEXTURE_BORDER_COLOR 120
#define GL_TEXTURE_COMPARE_FUNC_ARB 121
#define GL_TEXTURE_COMPARE_MODE_ARB 122
#define GL_TEXTURE_COMPRESSED_IMAGE_SIZE 123
#define GL_TEXTURE_COMPRESSION_HINT 124
#define GL_TEXTURE_CUBE_MAP 125
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X 126
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 127
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 128
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X 129
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 130
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y 131
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z 132
#define GL_TEXTURE_DEPTH 133
#define GL_TEXTURE_GEN_MODE 134
#define GL_TEXTURE_GEN_Q 135
#define GL_TEXTURE_GEN_R 136
#define GL_TEXTURE_GEN_S 137
#define GL_TEXTURE_GEN_T 138
#define GL_TEXTURE_GREEN_SIZE 139
#define GL_TEXTURE_HEIGHT 140
#define GL_TEXTURE_INTENSITY_SIZE 141
#define GL_TEXTURE_INTERNAL_FORMAT 142
#define GL_TEXTURE_LUMINANCE_SIZE 143
#define GL_TEXTURE_MAX_LEVEL 144
#define GL_TEXTURE_RED_SIZE 145
#define GL_TEXTURE_WIDTH 146
#define GL_TEXTURE_WRAP_R 147
#define GL_UNSIGNED_INT 148
#define GL_UNSIGNED_INT_24_8_EXT 149
#define GL_VERTEX_BLEND_ARB 150
#define GL_WEIGHT_ARRAY_ARB 151
#define GL_WEIGHT_SUM_UNITY_ARB 152
#define GL_DEPTH24_STENCIL8_EXT 153
