/*
 * This file was generated by:
 * built/tmp/interrogate/interrogate/interrogate -srcdir panda/src/gsgbase -Ipanda/src/gsgbase -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -D__attribute__(x)= -D_LP64 -oc built/tmp/libp3gsgbase_igate.cxx -od built/pandac/input/libp3gsgbase.in -fnames -string -refcount -assert -python-native -Sbuilt/include/parser-inc -Ipanda/src/gsgbase -Sbuilt/tmp -Sbuilt/include -module panda3d.core -library libp3gsgbase config_gsgbase.h graphicsOutputBase.h graphicsStateGuardianBase.h p3gsgbase_composite1.cxx
 *
 */

/* Generated by CMake.  DO NOT EDIT. */

// input file /project/src/interrogatedb/py_panda.h
#line 1 "/project/src/interrogatedb/py_compat.h"
/**
 * @file py_compat.h
 * @author rdb
 * @date 2017-12-02
 */

#ifndef PY_COMPAT_H
#define PY_COMPAT_H

#include "dtoolbase.h"

#ifdef HAVE_PYTHON

// The contents of this file were originally part of py_panda.h.  It
// specifically contains polyfills that are required to maintain compatibility
// with Python 2 and older versions of Python 3.

// These compatibility hacks are sorted by Python version that removes the
// need for the respective hack.

#ifdef _POSIX_C_SOURCE
#  undef _POSIX_C_SOURCE
#endif

#ifdef _XOPEN_SOURCE
#  undef _XOPEN_SOURCE
#endif

// See PEP 353
#define PY_SSIZE_T_CLEAN 1

#include <Python.h>

#ifndef LINK_ALL_STATIC
#  define EXPCL_PYPANDA
#elif defined(__GNUC__)
#  define EXPCL_PYPANDA __attribute__((weak))
#else
#  define EXPCL_PYPANDA extern inline
#endif

/* Python 2.4 */

// 2.4 macros which aren't available in 2.3
#ifndef Py_RETURN_NONE
#  define Py_RETURN_NONE return Py_INCREF(Py_None), Py_None
#endif

#ifndef Py_RETURN_TRUE
#  define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
#endif

#ifndef Py_RETURN_FALSE
#  define Py_RETURN_FALSE return Py_INCREF(Py_False), Py_False
#endif

/* Python 2.5 */

// Prior to Python 2.5, we didn't have Py_ssize_t.
#if PY_VERSION_HEX < 0x02050000
typedef int Py_ssize_t;
#  define PyInt_FromSsize_t PyInt_FromLong
#  define PyInt_AsSsize_t PyInt_AsLong
#endif

/* Python 2.6 */

#if PY_VERSION_HEX < 0x02060000
#  define Py_TYPE(ob) (((PyObject*)(ob))->ob_type)
#endif

/* Python 2.7, 3.1 */

#ifndef PyVarObject_HEAD_INIT
  #define PyVarObject_HEAD_INIT(type, size) \
    PyObject_HEAD_INIT(type) size,
#endif

/* Python 2.7, 3.2 */

#if PY_VERSION_HEX < 0x03020000
#  define PyErr_NewExceptionWithDoc(name, doc, base, dict) \
          PyErr_NewException(name, base, dict)
#endif

/* Python 3.0 */

// Always on in Python 3
#ifndef Py_TPFLAGS_CHECKTYPES
#  define Py_TPFLAGS_CHECKTYPES 0
#endif

// Macros for writing code that will compile in both versions.
#if PY_MAJOR_VERSION >= 3
#  define nb_nonzero nb_bool
#  define nb_divide nb_true_divide
#  define nb_inplace_divide nb_inplace_true_divide

#  define PyLongOrInt_Check(x) PyLong_Check(x)
#  define PyLongOrInt_AS_LONG PyLong_AS_LONG
#  define PyInt_Check PyLong_Check
#  define PyInt_AsLong PyLong_AsLong
#  define PyInt_AS_LONG PyLong_AS_LONG
#  define PyLongOrInt_AsSize_t PyLong_AsSize_t
#else
#  define PyLongOrInt_Check(x) (PyInt_Check(x) || PyLong_Check(x))
// PyInt_FromSize_t automatically picks the right type.
#  define PyLongOrInt_AS_LONG PyInt_AsLong

EXPCL_PYPANDA size_t PyLongOrInt_AsSize_t(PyObject *);
#endif

// Which character to use in PyArg_ParseTuple et al for a byte string.
#if PY_MAJOR_VERSION >= 3
#  define FMTCHAR_BYTES "y"
#else
#  define FMTCHAR_BYTES "s"
#endif

/* Python 3.2 */

#if PY_VERSION_HEX < 0x03020000
typedef long Py_hash_t;
#endif

/* Python 3.3 */

#if PY_MAJOR_VERSION >= 3
// Python versions before 3.3 did not define this.
#  if PY_VERSION_HEX < 0x03030000
#    define PyUnicode_AsUTF8 _PyUnicode_AsString
#    define PyUnicode_AsUTF8AndSize _PyUnicode_AsStringAndSize
#  endif
#endif

/* Python 3.4 */
#if PY_VERSION_HEX < 0x03040000
#define PyGILState_Check() (PyGILState_GetThisThreadState() == _PyThreadState_Current)
#endif

/* Python 3.6 */

#if PY_VERSION_HEX < 0x03080000 && !defined(_PyObject_CallNoArg)
#  define _PyObject_CallNoArg PyObject_CallNoArgs
#endif

#if PY_VERSION_HEX < 0x03080000 && !defined(_PyObject_FastCall)
INLINE PyObject *_PyObject_FastCall(PyObject *func, PyObject **args, Py_ssize_t nargs) {
  PyObject *tuple = PyTuple_New(nargs);
  for (Py_ssize_t i = 0; i < nargs; ++i) {
    PyTuple_SET_ITEM(tuple, i, args[i]);
    Py_INCREF(args[i]);
  }
  PyObject *result = PyObject_Call(func, tuple, nullptr);
  Py_DECREF(tuple);
  return result;
}
#  define _PyObject_FastCall _PyObject_FastCall
#endif

// Python versions before 3.6 didn't require longlong support to be enabled.
#ifndef HAVE_LONG_LONG
#  define PyLong_FromLongLong(x) PyLong_FromLong((long) (x))
#  define PyLong_FromUnsignedLongLong(x) PyLong_FromUnsignedLong((unsigned long) (x))
#  define PyLong_AsLongLong(x) PyLong_AsLong(x)
#  define PyLong_AsUnsignedLongLong(x) PyLong_AsUnsignedLong(x)
#  define PyLong_AsUnsignedLongLongMask(x) PyLong_AsUnsignedLongMask(x)
#  define PyLong_AsLongLongAndOverflow(x) PyLong_AsLongAndOverflow(x)
#endif

/* Python 3.7 */

#ifndef PyDict_GET_SIZE
#  define PyDict_GET_SIZE(mp) (((PyDictObject *)mp)->ma_used)
#endif

#ifndef Py_RETURN_RICHCOMPARE
#  define Py_RETURN_RICHCOMPARE(val1, val2, op)                         \
  do {                                                                  \
    switch (op) {                                                       \
    NODEFAULT                                                           \
    case Py_EQ: if ((val1) == (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;  \
    case Py_NE: if ((val1) != (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;  \
    case Py_LT: if ((val1) < (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;   \
    case Py_GT: if ((val1) > (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;   \
    case Py_LE: if ((val1) <= (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;  \
    case Py_GE: if ((val1) >= (val2)) Py_RETURN_TRUE; Py_RETURN_FALSE;  \
    }                                                                   \
  } while (0)
#endif

#if PY_VERSION_HEX < 0x03070000
INLINE PyObject *PyImport_GetModule(PyObject *name) {
  PyObject *modules = PyImport_GetModuleDict();
  if (modules != nullptr) {
    PyObject *module = PyDict_GetItem(modules, name);
    if (module != nullptr) {
      Py_INCREF(module);
      return module;
    }
  }
  return nullptr;
}
#endif

/* Python 3.8 */
#if PY_VERSION_HEX < 0x03080000
INLINE PyObject *_PyLong_Rshift(PyObject *a, size_t shiftby) {
  PyObject *b = PyLong_FromLong(shiftby);
  PyObject *result = PyNumber_Rshift(a, b);
  Py_DECREF(b);
  return result;
}
INLINE PyObject *_PyLong_Lshift(PyObject *a, size_t shiftby) {
  PyObject *b = PyLong_FromLong(shiftby);
  PyObject *result = PyNumber_Lshift(a, b);
  Py_DECREF(b);
  return result;
}
#endif

/* Python 3.9 */

#if PY_VERSION_HEX < 0x030900A4 && !defined(Py_IS_TYPE)
#  define Py_IS_TYPE(ob, type) (Py_TYPE((PyObject *)ob) == type)
#endif

#ifndef PyCFunction_CheckExact
#  define PyCFunction_CheckExact(op) (Py_IS_TYPE(op, &PyCFunction_Type))
#endif

#if PY_VERSION_HEX < 0x03090000
INLINE PyObject *PyObject_CallNoArgs(PyObject *func) {
#if PY_VERSION_HEX >= 0x03080000
  return _PyObject_Vectorcall(func, nullptr, 0, nullptr);
#elif PY_VERSION_HEX >= 0x03070000
  return _PyObject_FastCallDict(func, nullptr, 0, nullptr);
#elif PY_VERSION_HEX >= 0x03060000
  return _PyObject_FastCall(func, nullptr, 0);
#else
  return PyObject_CallObject(func, nullptr);
#endif
}

INLINE PyObject *PyObject_CallOneArg(PyObject *callable, PyObject *arg) {
#if PY_VERSION_HEX >= 0x03060000
  return _PyObject_FastCall(callable, &arg, 1);
#else
  return PyObject_CallFunctionObjArgs(callable, arg, nullptr);
#endif
}

INLINE PyObject *PyObject_CallMethodNoArgs(PyObject *obj, PyObject *name) {
  return PyObject_CallMethodObjArgs(obj, name, nullptr);
}

INLINE PyObject *PyObject_CallMethodOneArg(PyObject *obj, PyObject *name, PyObject *arg) {
  return PyObject_CallMethodObjArgs(obj, name, arg, nullptr);
}

INLINE int PyObject_GC_IsTracked(PyObject *obj) {
  return _PyObject_GC_IS_TRACKED(obj);
}
#endif

/* Python 3.10 */

#if PY_VERSION_HEX < 0x030A0000
INLINE int PyModule_AddObjectRef(PyObject *module, const char *name, PyObject *value) {
  int ret = PyModule_AddObject(module, name, value);
  if (ret == 0) {
    Py_INCREF(value);
  }
  return ret;
}

ALWAYS_INLINE PyObject *Py_NewRef(PyObject *obj) {
  Py_INCREF(obj);
  return obj;
}

ALWAYS_INLINE PyObject *Py_XNewRef(PyObject *obj) {
  Py_XINCREF(obj);
  return obj;
}
#endif

/* Python 3.11 */

#if PY_VERSION_HEX < 0x030B0000
INLINE PyObject *PyType_GetName(PyTypeObject *type) {
  return PyObject_GetAttrString((PyObject *)type, "__name__");
}

INLINE PyObject *PyType_GetQualName(PyTypeObject *type) {
  return PyObject_GetAttrString((PyObject *)type, "__qualname__");
}
#endif

/* Python 3.12 */

#if PY_VERSION_HEX < 0x030C0000
#  define PyLong_IsNonNegative(value) (Py_SIZE((value)) >= 0)
#else
INLINE bool PyLong_IsNonNegative(PyObject *value) {
  int overflow = 0;
  long longval = PyLong_AsLongAndOverflow(value, &overflow);
  return overflow == 1 || longval >= 0;
}
#endif

/* Python 3.13 */

#if PY_VERSION_HEX < 0x030D00A1
#  define PyLong_AsInt(x) (_PyLong_AsInt(x))
#endif

#if PY_VERSION_HEX < 0x030D00A1
ALWAYS_INLINE int
PyModule_Add(PyObject *mod, const char *name, PyObject *value) {
  int res = PyModule_AddObjectRef(mod, name, value);
  Py_XDECREF(value);
  return res;
}
#endif

#if PY_VERSION_HEX < 0x030D00A1
INLINE int
PyDict_GetItemRef(PyObject *mp, PyObject *key, PyObject **result) {
#if PY_MAJOR_VERSION >= 3
  PyObject *item = PyDict_GetItemWithError(mp, key);
#else
  PyObject *item = _PyDict_GetItemWithError(mp, key);
#endif
  if (item != nullptr) {
    *result = Py_NewRef(item);
    return 1;
  }
  *result = nullptr;
  return PyErr_Occurred() ? -1 : 0;
}

INLINE int
PyDict_GetItemStringRef(PyObject *mp, const char *key, PyObject **result) {
  PyObject *item = nullptr;
#if PY_MAJOR_VERSION >= 3
  PyObject *key_obj = PyUnicode_FromString(key);
  item = key_obj ? PyDict_GetItemWithError(mp, key_obj) : nullptr;
#else
  PyObject *key_obj = PyString_FromString(key);
  item = key_obj ? _PyDict_GetItemWithError(mp, key_obj) : nullptr;
#endif
  Py_DECREF(key_obj);
  if (item != nullptr) {
    *result = Py_NewRef(item);
    return 1;
  }
  *result = nullptr;
  return PyErr_Occurred() ? -1 : 0;
}
#endif

#if PY_VERSION_HEX >= 0x03050200 && PY_VERSION_HEX < 0x030D00A1
#  define PyThreadState_GetUnchecked() (_PyThreadState_UncheckedGet())
#endif

#if PY_VERSION_HEX < 0x030D00A2
#  define PyList_Extend(list, iterable) (PyList_SetSlice((list), PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, (iterable)))
#  define PyList_Clear(list) (PyList_SetSlice((list), 0, PY_SSIZE_T_MAX, nullptr))
#endif

#if PY_VERSION_HEX < 0x030D00A4
#  define PyList_GetItemRef(op, index) (Py_XNewRef(PyList_GetItem((op), (index))))
#endif

#if PY_VERSION_HEX < 0x030D00B3
#  define Py_BEGIN_CRITICAL_SECTION(op) {
#  define Py_END_CRITICAL_SECTION() }
#  define Py_BEGIN_CRITICAL_SECTION2(a, b) {
#  define Py_END_CRITICAL_SECTION2() }
#endif

/* Python 3.14 */

#if PY_VERSION_HEX < 0x030E00A8
#  define PyUnstable_Object_IsUniquelyReferenced(op) (Py_REFCNT((op)) == 1)
#endif

/* Other Python implementations */

#endif  // HAVE_PYTHON

#endif  // PY_COMPAT_H

#line 1 "/project/src/interrogatedb/py_panda.h"
/**
 * @file py_panda.h
 */

#ifndef PY_PANDA_H_
#define PY_PANDA_H_

#include <set>
#include <map>
#include <string>
#include <vector>

#include "pnotify.h"
#include "register_type.h"

#if defined(HAVE_PYTHON) && !defined(CPPPARSER)

// py_compat.h includes Python.h.
//#include "py_compat.h"
#include <structmember.h>

// this is tempory .. untill this is glued better into the panda build system

#if defined(_WIN32) && !defined(LINK_ALL_STATIC)
#define EXPORT_THIS __declspec(dllexport)
#define IMPORT_THIS extern __declspec(dllimport)
#else
#define EXPORT_THIS
#define IMPORT_THIS extern
#endif

struct Dtool_PyInstDef;
struct Dtool_PyTypedObject;

// used to stamp dtool instance..
#define PY_PANDA_SIGNATURE 0xbeaf
typedef void *(*UpcastFunction)(PyObject *,Dtool_PyTypedObject *);
typedef PyObject *(*WrapFunction)(void *, PyTypeObject *);
typedef void *(*CoerceFunction)(PyObject *, void *);
typedef void (*ModuleClassInitFunction)(PyObject *module);

// INSTANCE CONTAINER FOR ALL panda py objects....
struct Dtool_PyInstDef {
  PyObject_HEAD

  // This is a pointer to the Dtool_PyTypedObject type.  It's tempting not to
  // store this and to instead use PY_TYPE(self) and upcast that, but that
  // breaks when someone inherits from our class in Python.
  struct Dtool_PyTypedObject *_My_Type;

  // Pointer to the underlying C++ object.
  void *_ptr_to_object;

  // This is always set to PY_PANDA_SIGNATURE, so that we can quickly detect
  // whether an object is a Panda object.
  unsigned short _signature;

  // True if we own the pointer and should delete it or unref it.
  bool _memory_rules;

  // True if this is a "const" pointer.
  bool _is_const;
};

// The Class Definition Structor For a Dtool python type.
struct Dtool_PyTypedObject {
  // Standard Python Features..
  PyTypeObject _PyType;

  // May be TypeHandle::none() to indicate a non-TypedObject class.
  TypeHandle _type;

  ModuleClassInitFunction _Dtool_ModuleClassInit;

  UpcastFunction _Dtool_UpcastInterface;    // The Upcast Function By Slot
  WrapFunction _Dtool_WrapInterface; // The Downcast Function By Slot

  CoerceFunction _Dtool_ConstCoerce;
  CoerceFunction _Dtool_Coerce;
};

// Extract the PyTypeObject pointer corresponding to a Dtool_PyTypedObject.
#define Dtool_GetPyTypeObject(type) (&(type)->_PyType)

// Use DtoolInstance_Check to check whether a PyObject* is a DtoolInstance.
#define DtoolInstance_Check(obj) \
  (Py_TYPE(obj)->tp_basicsize >= (int)sizeof(Dtool_PyInstDef) && \
   ((Dtool_PyInstDef *)obj)->_signature == PY_PANDA_SIGNATURE)

// These macros access the DtoolInstance without error checking.
#define DtoolInstance_TYPE(obj) (((Dtool_PyInstDef *)obj)->_My_Type)
#define DtoolInstance_IS_CONST(obj) (((Dtool_PyInstDef *)obj)->_is_const)
#define DtoolInstance_VOID_PTR(obj) (((Dtool_PyInstDef *)obj)->_ptr_to_object)
#define DtoolInstance_INIT_PTR(obj, ptr) { ((Dtool_PyInstDef *)obj)->_ptr_to_object = (void*)(ptr); }
#define DtoolInstance_UPCAST(obj, type) (((Dtool_PyInstDef *)(obj))->_My_Type->_Dtool_UpcastInterface((obj), &(type)))

class DtoolProxy {
public:
  mutable PyObject *_self;
  TypeHandle _type;
};

/**

 */
EXPCL_PYPANDA void DTOOL_Call_ExtractThisPointerForType(PyObject *self, Dtool_PyTypedObject *classdef, void **answer);

EXPCL_PYPANDA void *DTOOL_Call_GetPointerThisClass(PyObject *self, Dtool_PyTypedObject *classdef, int param, const std::string &function_name, bool const_ok, bool report_errors);

EXPCL_PYPANDA bool Dtool_Call_ExtractThisPointer(PyObject *self, Dtool_PyTypedObject &classdef, void **answer);

EXPCL_PYPANDA bool Dtool_Call_ExtractThisPointer_NonConst(PyObject *self, Dtool_PyTypedObject &classdef,
                                                          void **answer, const char *method_name);

template<class T> INLINE bool DtoolInstance_GetPointer(PyObject *self, T *&into);
template<class T> INLINE bool DtoolInstance_GetPointer(PyObject *self, T *&into, Dtool_PyTypedObject &classdef);

EXPCL_PYPANDA PyObject *Dtool_Raise_AssertionError();
EXPCL_PYPANDA PyObject *Dtool_Raise_TypeError(const char *message);
EXPCL_PYPANDA PyObject *Dtool_Raise_ArgTypeError(PyObject *obj, int param, const char *function_name, const char *type_name);
EXPCL_PYPANDA PyObject *Dtool_Raise_AttributeError(PyObject *obj, const char *attribute);
EXPCL_PYPANDA int Dtool_Raise_CantDeleteAttributeError(const char *attribute);

EXPCL_PYPANDA PyObject *_Dtool_Raise_BadArgumentsError();
EXPCL_PYPANDA PyObject *_Dtool_Raise_BadArgumentsError(const char *message);
EXPCL_PYPANDA int _Dtool_Raise_BadArgumentsError_Int();
EXPCL_PYPANDA int _Dtool_Raise_BadArgumentsError_Int(const char *message);
#ifdef NDEBUG
// Define it to a function that just prints a generic message.
#define Dtool_Raise_BadArgumentsError(x) _Dtool_Raise_BadArgumentsError()
#define Dtool_Raise_BadArgumentsError_Int(x) _Dtool_Raise_BadArgumentsError_Int()
#else
// Expand this to a TypeError listing all of the overloads.
#define Dtool_Raise_BadArgumentsError(x) _Dtool_Raise_BadArgumentsError(x)
#define Dtool_Raise_BadArgumentsError_Int(x) _Dtool_Raise_BadArgumentsError_Int(x)
#endif

/**

 */
EXPCL_PYPANDA PyObject *DTool_CreatePyInstanceTyped(void *local_this_in, Dtool_PyTypedObject &known_class_type, bool memory_rules, bool is_const, int RunTimeType);

// DTool_CreatePyInstance .. wrapper function to finalize the existance of a
// general dtool py instance..
EXPCL_PYPANDA PyObject *DTool_CreatePyInstance(void *local_this, Dtool_PyTypedObject &in_classdef, bool memory_rules, bool is_const);

// These template methods allow use when the Dtool_PyTypedObject is not known.
// They require a get_class_type() to be defined for the class.
template<class T> INLINE PyObject *DTool_CreatePyInstance(const T *obj, bool memory_rules);
template<class T> INLINE PyObject *DTool_CreatePyInstance(T *obj, bool memory_rules);
template<class T> INLINE PyObject *DTool_CreatePyInstanceTyped(const T *obj, bool memory_rules);
template<class T> INLINE PyObject *DTool_CreatePyInstanceTyped(T *obj, bool memory_rules);

// The finalizer for simple instances.
INLINE int DTool_PyInit_Finalize(PyObject *self, void *This, Dtool_PyTypedObject *type, bool memory_rules, bool is_const);

/**
 * These functions convert a C++ value into the corresponding Python object.
 * This used to be generated by the code generator, but it seems more reliable
 * and maintainable to define these as overloads and have the compiler sort
 * it out.
 */
ALWAYS_INLINE PyObject *Dtool_WrapValue(int value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned int value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(long value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned long value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(long long value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned long long value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(bool value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(double value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const char *value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const wchar_t *value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::string &value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::wstring &value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::string *value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::wstring *value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(char value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(wchar_t value);
ALWAYS_INLINE PyObject *Dtool_WrapValue(std::nullptr_t);
ALWAYS_INLINE PyObject *Dtool_WrapValue(PyObject *value);
template<class Allocator>
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::vector<unsigned char, Allocator> &value);

#if PY_MAJOR_VERSION >= 0x02060000
ALWAYS_INLINE PyObject *Dtool_WrapValue(Py_buffer *value);
#endif

template<class T1, class T2>
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::pair<T1, T2> &value);

EXPCL_PYPANDA Dtool_PyTypedObject *Dtool_GetSuperBase();

/**
 * Creates a Python generator object from a next() function.
 */
EXPCL_PYPANDA PyObject *Dtool_NewGenerator(PyObject *self, iternextfunc func);

//#include "py_panda.I" inlined
#line 1 "/project/src/interrogatedb/py_panda.I"
/**
 * @file py_panda.I
 * @author rdb
 * @date 2016-06-06
 */

#ifdef _MSC_VER
#define _IS_FINAL(T) (__is_sealed(T))
#elif defined(__GNUC__)
#define _IS_FINAL(T) (__is_final(T))
#else
#define _IS_FINAL(T) (0)
#endif

/**
 * Template function that can be used to extract any TypedObject pointer from
 * a wrapped Python object.
 */
template<class T> INLINE bool
DtoolInstance_GetPointer(PyObject *self, T *&into) {
  if (DtoolInstance_Check(self)) {
    Dtool_PyTypedObject *target_class = (Dtool_PyTypedObject *)get_type_handle(T).get_python_type();
    if (target_class != nullptr) {
      if (_IS_FINAL(T)) {
        if (DtoolInstance_TYPE(self) == target_class) {
          into = (T *)DtoolInstance_VOID_PTR(self);
        } else {
          return false;
        }
      } else {
        into = (T *)DtoolInstance_UPCAST(self, *target_class);
      }
      return (into != nullptr);
    }
  }
  into = nullptr;
  return false;
}

/**
 * Template function that can be used to extract any TypedObject pointer from
 * a wrapped Python object.  In this case, the Dtool_PyTypedObject is known.
 */
template<class T> INLINE bool
DtoolInstance_GetPointer(PyObject *self, T *&into, Dtool_PyTypedObject &target_class) {
  if (DtoolInstance_Check(self)) {
    if (_IS_FINAL(T)) {
      if (DtoolInstance_TYPE(self) == &target_class) {
        into = (T *)DtoolInstance_VOID_PTR(self);
      } else {
        return false;
      }
    } else {
      into = (T *)DtoolInstance_UPCAST(self, target_class);
    }
    return (into != nullptr);
  }
  into = nullptr;
  return false;
}

/**
 * These functions wrap a pointer for a class that defines get_type_handle().
 */
template<class T> INLINE PyObject *
DTool_CreatePyInstance(const T *obj, bool memory_rules) {
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)get_type_handle(T).wrap_python(obj);
  nassertr(self != nullptr, nullptr);
  self->_memory_rules = memory_rules;
  self->_is_const = true;
  return (PyObject *)self;
}

template<class T> INLINE PyObject *
DTool_CreatePyInstance(T *obj, bool memory_rules) {
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)get_type_handle(T).wrap_python(obj);
  nassertr(self != nullptr, nullptr);
  self->_memory_rules = memory_rules;
  self->_is_const = false;
  return (PyObject *)self;
}

template<class T> INLINE PyObject *
DTool_CreatePyInstanceTyped(const T *obj, bool memory_rules) {
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)get_type_handle(T).wrap_python(obj);
  nassertr(self != nullptr, nullptr);
  self->_memory_rules = memory_rules;
  self->_is_const = true;
  return (PyObject *)self;
}

template<class T> INLINE PyObject *
DTool_CreatePyInstanceTyped(T *obj, bool memory_rules) {
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)get_type_handle(T).wrap_python(obj);
  nassertr(self != nullptr, nullptr);
  self->_memory_rules = memory_rules;
  self->_is_const = false;
  return (PyObject *)self;
}

/**
 * Finishes initializing the Dtool_PyInstDef.
 */
INLINE int
DTool_PyInit_Finalize(PyObject *self, void *local_this, Dtool_PyTypedObject *type, bool memory_rules, bool is_const) {
  ((Dtool_PyInstDef *)self)->_My_Type = type;
  ((Dtool_PyInstDef *)self)->_ptr_to_object = local_this;
  ((Dtool_PyInstDef *)self)->_memory_rules = memory_rules;
  ((Dtool_PyInstDef *)self)->_is_const = is_const;
  return 0;
}

/**
 * The following functions wrap an arbitrary C++ value into a PyObject.
 */
ALWAYS_INLINE PyObject *Dtool_WrapValue(int value) {
#if PY_MAJOR_VERSION >= 3
  return PyLong_FromLong((long)value);
#else
  return PyInt_FromLong((long)value);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned int value) {
#if PY_MAJOR_VERSION >= 3 && SIZEOF_INT < SIZEOF_LONG
  return PyLong_FromLong((long)value);
#elif PY_MAJOR_VERSION >= 3
  return PyLong_FromUnsignedLong((unsigned long)value);
#elif SIZEOF_INT < SIZEOF_LONG
  return PyInt_FromLong((long)value);
#else
  return (value > LONG_MAX)
    ? PyLong_FromUnsignedLong((unsigned long)value)
    : PyInt_FromLong((long)value);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(long value) {
#if PY_MAJOR_VERSION >= 3
  return PyLong_FromLong(value);
#else
  return PyInt_FromLong(value);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned long value) {
#if PY_MAJOR_VERSION >= 3
  return PyLong_FromUnsignedLong(value);
#else
  return (value > LONG_MAX)
    ? PyLong_FromUnsignedLong(value)
    : PyInt_FromLong((long)value);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(long long value) {
  return PyLong_FromLongLong(value);
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(unsigned long long value) {
  // size_t is sometimes defined as unsigned long long, and we want to map
  // that to int in Python 2 so it can be returned from a __len__.
#if PY_MAJOR_VERSION >= 3
  return PyLong_FromUnsignedLongLong(value);
#else
  return (value > LONG_MAX)
    ? PyLong_FromUnsignedLongLong(value)
    : PyInt_FromLong((long)value);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(bool value) {
  PyObject *result = (value ? Py_True : Py_False);
  return Py_NewRef(result);
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(double value) {
  return PyFloat_FromDouble(value);
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const char *value) {
  if (value == nullptr) {
    return Py_NewRef(Py_None);
  } else {
#if PY_MAJOR_VERSION >= 3
    return PyUnicode_FromString(value);
#else
    return PyString_FromString(value);
#endif
  }
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const wchar_t *value) {
  if (value == nullptr) {
    return Py_NewRef(Py_None);
  } else {
    return PyUnicode_FromWideChar(value, (Py_ssize_t)wcslen(value));
  }
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::string &value) {
#if PY_MAJOR_VERSION >= 3
  return PyUnicode_FromStringAndSize(value.data(), (Py_ssize_t)value.length());
#else
  return PyString_FromStringAndSize(value.data(), (Py_ssize_t)value.length());
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::wstring &value) {
  return PyUnicode_FromWideChar(value.data(), (Py_ssize_t)value.length());
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::string *value) {
  if (value == nullptr) {
    return Py_NewRef(Py_None);
  } else {
#if PY_MAJOR_VERSION >= 3
    return PyUnicode_FromStringAndSize(value->data(), (Py_ssize_t)value->length());
#else
    return PyString_FromStringAndSize(value->data(), (Py_ssize_t)value->length());
#endif
  }
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::wstring *value) {
  if (value == nullptr) {
    return Py_NewRef(Py_None);
  } else {
    return PyUnicode_FromWideChar(value->data(), (Py_ssize_t)value->length());
  }
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(char value) {
#if PY_MAJOR_VERSION >= 3
  return PyUnicode_FromStringAndSize(&value, 1);
#else
  return PyString_FromStringAndSize(&value, 1);
#endif
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(wchar_t value) {
  return PyUnicode_FromWideChar(&value, 1);
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(std::nullptr_t) {
  return Py_NewRef(Py_None);
}

ALWAYS_INLINE PyObject *Dtool_WrapValue(PyObject *value) {
  return value;
}

template<class Allocator>
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::vector<unsigned char, Allocator> &value) {
#if PY_MAJOR_VERSION >= 3
  return PyBytes_FromStringAndSize((char *)value.data(), (Py_ssize_t)value.size());
#else
  return PyString_FromStringAndSize((char *)value.data(), (Py_ssize_t)value.size());
#endif
}

#if PY_MAJOR_VERSION >= 0x02060000
ALWAYS_INLINE PyObject *Dtool_WrapValue(Py_buffer *value) {
  if (value == nullptr) {
    return value;
  } else {
    return PyMemoryView_FromBuffer(value);
  }
}
#endif

template<class T1, class T2>
ALWAYS_INLINE PyObject *Dtool_WrapValue(const std::pair<T1, T2> &value) {
  PyObject *tuple = PyTuple_New(2);
  PyTuple_SET_ITEM(tuple, 0, Dtool_WrapValue(value.first));
  PyTuple_SET_ITEM(tuple, 1, Dtool_WrapValue(value.second));
  return tuple;
}


#endif  // HAVE_PYTHON && !CPPPARSER

#endif // PY_PANDA_H_

// input file /project/src/interrogatedb/py_support.h
#line 1 "/project/src/interrogatedb/py_wrappers.h"
/**
 * @file py_wrappers.h
 * @author rdb
 * @date 2017-11-26
 */

#ifndef PY_WRAPPERS_H
#define PY_WRAPPERS_H

//#include "py_panda.h"

#ifdef HAVE_PYTHON

/**
 * These classes are returned from properties that require a subscript
 * interface, ie. something.children[i] = 3.
 */
struct Dtool_WrapperBase {
  PyObject_HEAD;
  PyObject *_self;
  const char *_name;
};

struct Dtool_SequenceWrapper {
  Dtool_WrapperBase _base;
  lenfunc _len_func;
  ssizeargfunc _getitem_func;
};

struct Dtool_MutableSequenceWrapper {
  Dtool_WrapperBase _base;
  lenfunc _len_func;
  ssizeargfunc _getitem_func;
  ssizeobjargproc _setitem_func;
  PyObject *(*_insert_func)(PyObject *, size_t, PyObject *);
};

struct Dtool_MappingWrapper {
  union {
    Dtool_WrapperBase _base;
    Dtool_SequenceWrapper _keys;
  };
  binaryfunc _getitem_func;
  objobjargproc _setitem_func;
};

struct Dtool_GeneratorWrapper {
  Dtool_WrapperBase _base;
  iternextfunc _iternext_func;
};

EXPCL_PYPANDA Dtool_SequenceWrapper *Dtool_NewSequenceWrapper(PyObject *self, const char *name);
EXPCL_PYPANDA Dtool_MutableSequenceWrapper *Dtool_NewMutableSequenceWrapper(PyObject *self, const char *name);
EXPCL_PYPANDA Dtool_MappingWrapper *Dtool_NewMappingWrapper(PyObject *self, const char *name);
EXPCL_PYPANDA Dtool_MappingWrapper *Dtool_NewMutableMappingWrapper(PyObject *self, const char *name);
EXPCL_PYPANDA PyObject *Dtool_NewStaticProperty(PyTypeObject *obj, const PyGetSetDef *getset);

#endif  // HAVE_PYTHON

#endif  // PY_WRAPPERS_H

#line 1 "/project/src/interrogatedb/py_support.h"
/**
 * @file py_support.h
 * @author rdb
 * @date 2025-09-03
 */

#ifndef PY_SUPPORT_H
#define PY_SUPPORT_H

/**
 * This header file is for helper functions that are only used by
 * interrogate-generated code, whereas py_panda.h is for code that may also
 * be used by extensions.
 */

#if defined(HAVE_PYTHON) && !defined(CPPPARSER)

//#include "py_panda.h"

using namespace std;

// This is now simply a forward declaration.  The actual definition is created
// by the code generator.
#define Define_Dtool_Class(MODULE_NAME, CLASS_NAME, PUBLIC_NAME) \
  extern Dtool_PyTypedObject Dtool_##CLASS_NAME;

// More Macro(s) to Implement class functions.. Usually used if C++ needs type
// information
#define Define_Dtool_new(CLASS_NAME,CNAME)\
static PyObject *Dtool_new_##CLASS_NAME(PyTypeObject *type, PyObject *args, PyObject *kwds) {\
  (void) args; (void) kwds;\
  PyObject *self = type->tp_alloc(type, 0);\
  ((Dtool_PyInstDef *)self)->_signature = PY_PANDA_SIGNATURE;\
  ((Dtool_PyInstDef *)self)->_My_Type = &Dtool_##CLASS_NAME;\
  return self;\
}

// The following used to be in the above macro, but it doesn't seem to be
// necessary as tp_alloc memsets the object to 0.
//  ((Dtool_PyInstDef *)self)->_ptr_to_object = NULL;
//  ((Dtool_PyInstDef *)self)->_memory_rules = false;
//  ((Dtool_PyInstDef *)self)->_is_const = false;

// Delete functions..
#ifdef NDEBUG
#define Define_Dtool_FreeInstance_Private(CLASS_NAME,CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  Py_TYPE(self)->tp_free(self);\
}
#else // NDEBUG
#define Define_Dtool_FreeInstance_Private(CLASS_NAME,CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  if (DtoolInstance_VOID_PTR(self) != nullptr) {\
    if (((Dtool_PyInstDef *)self)->_memory_rules) {\
      std::cerr << "Detected leak for " << #CLASS_NAME \
           << " which interrogate cannot delete.\n"; \
    }\
  }\
  Py_TYPE(self)->tp_free(self);\
}
#endif  // NDEBUG

#define Define_Dtool_FreeInstance(CLASS_NAME,CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  if (DtoolInstance_VOID_PTR(self) != nullptr) {\
    if (((Dtool_PyInstDef *)self)->_memory_rules) {\
      delete (CNAME *)DtoolInstance_VOID_PTR(self);\
    }\
  }\
  Py_TYPE(self)->tp_free(self);\
}

#define Define_Dtool_FreeInstanceRef(CLASS_NAME,CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  if (DtoolInstance_VOID_PTR(self) != nullptr) {\
    if (((Dtool_PyInstDef *)self)->_memory_rules) {\
      unref_delete((CNAME *)DtoolInstance_VOID_PTR(self));\
    }\
  }\
  Py_TYPE(self)->tp_free(self);\
}

#define Define_Dtool_FreeInstanceRef_Private(CLASS_NAME,CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  if (DtoolInstance_VOID_PTR(self) != nullptr) {\
    if (((Dtool_PyInstDef *)self)->_memory_rules) {\
      unref_delete((ReferenceCount *)(CNAME *)DtoolInstance_VOID_PTR(self));\
    }\
  }\
  Py_TYPE(self)->tp_free(self);\
}

#define Define_Dtool_Simple_FreeInstance(CLASS_NAME, CNAME)\
static void Dtool_FreeInstance_##CLASS_NAME(PyObject *self) {\
  ((Dtool_InstDef_##CLASS_NAME *)self)->_value.~##CLASS_NAME();\
  Py_TYPE(self)->tp_free(self);\

#if PY_VERSION_HEX >= 0x030d0000
class Dtool_TypeMap : public std::map<std::string, Dtool_PyTypedObject *> {
public:
  PyMutex _lock { 0 };
};
#else
typedef std::map<std::string, Dtool_PyTypedObject *> Dtool_TypeMap;
#endif

EXPCL_PYPANDA Dtool_TypeMap *Dtool_GetGlobalTypeMap();


EXPCL_PYPANDA void DtoolProxy_Init(DtoolProxy *proxy, PyObject *self,
                                   Dtool_PyTypedObject &classdef,
                                   TypeRegistry::PythonWrapFunc *wrap_func);

INLINE Py_hash_t DtoolInstance_HashPointer(PyObject *self);
INLINE int DtoolInstance_ComparePointers(PyObject *v1, PyObject *v2);
INLINE PyObject *DtoolInstance_RichComparePointers(PyObject *v1, PyObject *v2, int op);

// Functions related to error reporting.
EXPCL_PYPANDA bool _Dtool_CheckErrorOccurred();

#ifdef NDEBUG
#define Dtool_CheckErrorOccurred() (UNLIKELY(PyErr_Occurred() != nullptr))
#else
#define Dtool_CheckErrorOccurred() (UNLIKELY(_Dtool_CheckErrorOccurred()))
#endif

// These functions are similar to Dtool_WrapValue, except that they also
// contain code for checking assertions and exceptions when compiling with
// NDEBUG mode on.
EXPCL_PYPANDA PyObject *_Dtool_Return_None();
EXPCL_PYPANDA PyObject *Dtool_Return_Bool(bool value);
EXPCL_PYPANDA PyObject *_Dtool_Return(PyObject *value);

#ifdef NDEBUG
#define Dtool_Return_None() (LIKELY(PyErr_Occurred() == nullptr) ? (Py_NewRef(Py_None)) : nullptr)
#define Dtool_Return(value) (LIKELY(PyErr_Occurred() == nullptr) ? value : nullptr)
#else
#define Dtool_Return_None() _Dtool_Return_None()
#define Dtool_Return(value) _Dtool_Return(value)
#endif

ALWAYS_INLINE void Dtool_Assign_PyObject(PyObject *&ptr, PyObject *value);

/**
 * Wrapper around Python 3.4's enum library, which does not have a C API.
 */
EXPCL_PYPANDA PyTypeObject *Dtool_EnumType_Create(const char *name, PyObject *names,
                                                  const char *module = nullptr);
INLINE long Dtool_EnumValue_AsLong(PyObject *value);

// Macro(s) class definition .. Used to allocate storage and init some values
// for a Dtool Py Type object.

// struct Dtool_PyTypedObject Dtool_##CLASS_NAME;

#define Define_Module_Class_Internal(MODULE_NAME,CLASS_NAME,CNAME)\
extern struct Dtool_PyTypedObject Dtool_##CLASS_NAME;\
static int Dtool_Init_##CLASS_NAME(PyObject *self, PyObject *args, PyObject *kwds);\
static PyObject *Dtool_new_##CLASS_NAME(PyTypeObject *type, PyObject *args, PyObject *kwds);

#define Define_Module_Class(MODULE_NAME,CLASS_NAME,CNAME,PUBLIC_NAME)\
Define_Module_Class_Internal(MODULE_NAME,CLASS_NAME,CNAME)\
Define_Dtool_new(CLASS_NAME,CNAME)\
Define_Dtool_FreeInstance(CLASS_NAME,CNAME)\
Define_Dtool_Class(MODULE_NAME,CLASS_NAME,PUBLIC_NAME)

#define Define_Module_Class_Private(MODULE_NAME,CLASS_NAME,CNAME,PUBLIC_NAME)\
Define_Module_Class_Internal(MODULE_NAME,CLASS_NAME,CNAME)\
Define_Dtool_new(CLASS_NAME,CNAME)\
Define_Dtool_FreeInstance_Private(CLASS_NAME,CNAME)\
Define_Dtool_Class(MODULE_NAME,CLASS_NAME,PUBLIC_NAME)

#define Define_Module_ClassRef_Private(MODULE_NAME,CLASS_NAME,CNAME,PUBLIC_NAME)\
Define_Module_Class_Internal(MODULE_NAME,CLASS_NAME,CNAME)\
Define_Dtool_new(CLASS_NAME,CNAME)\
Define_Dtool_FreeInstanceRef_Private(CLASS_NAME,CNAME)\
Define_Dtool_Class(MODULE_NAME,CLASS_NAME,PUBLIC_NAME)

#define Define_Module_ClassRef(MODULE_NAME,CLASS_NAME,CNAME,PUBLIC_NAME)\
Define_Module_Class_Internal(MODULE_NAME,CLASS_NAME,CNAME)\
Define_Dtool_new(CLASS_NAME,CNAME)\
Define_Dtool_FreeInstanceRef(CLASS_NAME,CNAME)\
Define_Dtool_Class(MODULE_NAME,CLASS_NAME,PUBLIC_NAME)

// A heler function to glu methed definition together .. that can not be done
// at code generation time becouse of multiple generation passes in
// interigate..
typedef std::map<std::string, PyMethodDef *> MethodDefmap;

// We need a way to runtime merge compile units into a python "Module" .. this
// is done with the fallowing structors and code.. along with the support of
// interigate_module

struct Dtool_TypeDef {
  const char *const name;
  Dtool_PyTypedObject *type;
};

struct LibraryDef {
  PyMethodDef *const _methods;
  const Dtool_TypeDef *const _types;
  Dtool_TypeDef *const _external_types;
  const struct InterrogateModuleDef *const _module_def;
};

#if PY_MAJOR_VERSION >= 3
EXPCL_PYPANDA PyObject *Dtool_PyModuleInitHelper(const LibraryDef *defs[], PyModuleDef *module_def);
#else
EXPCL_PYPANDA PyObject *Dtool_PyModuleInitHelper(const LibraryDef *defs[], const char *modulename);
#endif

// HACK.... Be carefull Dtool_BorrowThisReference This function can be used to
// grab the "THIS" pointer from an object and use it Required to support fom
// historical inharatence in the for of "is this instance of"..
EXPCL_PYPANDA PyObject *Dtool_BorrowThisReference(PyObject *self, PyObject *args);

#define DTOOL_PyObject_HashPointer DtoolInstance_HashPointer
#define DTOOL_PyObject_ComparePointers DtoolInstance_ComparePointers

EXPCL_PYPANDA PyObject *
Dtool_AddToDictionary(PyObject *self1, PyObject *args);

EXPCL_PYPANDA PyObject *
copy_from_make_copy(PyObject *self, PyObject *noargs);

EXPCL_PYPANDA PyObject *
copy_from_copy_constructor(PyObject *self, PyObject *noargs);

EXPCL_PYPANDA PyObject *
map_deepcopy_to_copy(PyObject *self, PyObject *args);

/**
 * These functions check whether the arguments passed to a function conform to
 * certain expectations.
 */
ALWAYS_INLINE bool Dtool_CheckNoArgs(PyObject *args);
ALWAYS_INLINE bool Dtool_CheckNoArgs(PyObject *args, PyObject *kwds);
EXPCL_PYPANDA bool Dtool_ExtractArg(PyObject **result, PyObject *args,
                                    PyObject *kwds, const char *keyword);
EXPCL_PYPANDA bool Dtool_ExtractArg(PyObject **result, PyObject *args,
                                    PyObject *kwds);
EXPCL_PYPANDA bool Dtool_ExtractOptionalArg(PyObject **result, PyObject *args,
                                            PyObject *kwds, const char *keyword);
EXPCL_PYPANDA bool Dtool_ExtractOptionalArg(PyObject **result, PyObject *args,
                                            PyObject *kwds);

//#include "py_support.I" inlined
#line 1 "/project/src/interrogatedb/py_support.I"
/**
 * @file py_support.I
 * @author rdb
 * @date 2025-09-03
 */

/**
 * Function to create a hash from a wrapped Python object.
 */
INLINE Py_hash_t DtoolInstance_HashPointer(PyObject *self) {
  if (self != nullptr && DtoolInstance_Check(self)) {
    return (Py_hash_t)(intptr_t)DtoolInstance_VOID_PTR(self);
  }
  return -1;
}

/**
 * Python 2-style comparison function that compares objects by pointer.
 */
INLINE int DtoolInstance_ComparePointers(PyObject *v1, PyObject *v2) {
  void *v1_this = DtoolInstance_Check(v1) ? DtoolInstance_VOID_PTR(v1) : nullptr;
  void *v2_this = DtoolInstance_Check(v2) ? DtoolInstance_VOID_PTR(v2) : nullptr;
  if (v1_this != nullptr && v2_this != nullptr) {
    return (v1_this > v2_this) - (v1_this < v2_this);
  } else {
    return (v1 > v2) - (v1 < v2);
  }
}

/**
 * Rich comparison function that compares objects by pointer.
 */
INLINE PyObject *DtoolInstance_RichComparePointers(PyObject *v1, PyObject *v2, int op) {
  int cmpval = DtoolInstance_ComparePointers(v1, v2);
  Py_RETURN_RICHCOMPARE(cmpval, 0, op);
}

/**
 * Utility function for assigning a PyObject pointer while managing refcounts.
 */
ALWAYS_INLINE void
Dtool_Assign_PyObject(PyObject *&ptr, PyObject *value) {
  PyObject *prev_value = ptr;
  if (prev_value != value) {
    ptr = Py_XNewRef(value);
    Py_XDECREF(prev_value);
  }
}

/**
 * Converts the enum value to a C long.
 */
INLINE long Dtool_EnumValue_AsLong(PyObject *value) {
  PyObject *val = PyObject_GetAttrString(value, "value");
  if (val != nullptr) {
    long as_long = PyLongOrInt_AS_LONG(val);
    Py_DECREF(val);
    return as_long;
  } else {
    return -1;
  }
}

/**
 * Checks that the tuple is empty.
 */
ALWAYS_INLINE bool
Dtool_CheckNoArgs(PyObject *args) {
  return PyTuple_GET_SIZE(args) == 0;
}

/**
 * Checks that the tuple is empty, and that the dict is empty or NULL.
 */
ALWAYS_INLINE bool
Dtool_CheckNoArgs(PyObject *args, PyObject *kwds) {
  return PyTuple_GET_SIZE(args) == 0 &&
    (kwds == nullptr || PyDict_GET_SIZE(kwds) == 0);
}


//#include "py_wrappers.h"

#endif  // HAVE_PYTHON && !CPPPARSER

#endif // PY_SUPPORT_H

// input file /project/src/interrogatedb/extension.h
#line 1 "/project/src/interrogatedb/extension.h"
/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file extension.h
 * @author rdb
 * @date 2013-09-11
 */

#ifndef EXTENSION_H
#define EXTENSION_H

#include "dtoolbase.h"

/**
 * This is where all extensions should derive from.  It defines the _self and
 * _this members that can be used from the extension method.
 */
template<class T>
class EXPCL_INTERROGATEDB ExtensionBase {
public:
  T * _this;
};

/**
 * The default class template does not define any methods.  Classes that are
 * extended should create a specialization of this class template.
 */
template<class T>
class Extension : public ExtensionBase<T> {
};

/**
 * Creates a new extension object for the given pointer that can then be used
 * to call extension methods, as follows: invoke_extension((MyClass)
 * *ptr).method()
 */
template<class T>
inline Extension<T>
invoke_extension(T *ptr) {
  Extension<T> ext;
  ext._this = ptr;
  return ext;
}

/**
 * The const version of the above function.
 */
template<class T>
inline const Extension<T>
invoke_extension(const T *ptr) {
  Extension<T> ext;
  ext._this = (T *) ptr;
  return ext;
}

#endif


#line 1354 "/home/kt/dev/panda3d/built/tmp/libp3gsgbase_igate.cxx"
#include "dtoolbase.h"
#include "interrogate_request.h"
#include "dconfig.h"
#include "pnotify.h"
#include <sstream>

#include "completionToken.h"
#include "config_gsgbase.h"
#include "graphicsOutputBase.h"
#include "graphicsStateGuardianBase.h"
#include "lightMutex.h"
#include "luse.h"
#include "nodeCachedReferenceCount.h"
#include "pandabase.h"
#include "patomic.h"
#include "small_vector.h"
#include "typedWritableReferenceCount.h"
#include "vector_uchar.h"

#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#define PY_SSIZE_T_CLEAN 1

#if PYTHON_FRAMEWORK
  #include <Python/Python.h>
#else
  #include "Python.h"
#endif

/**
 * Forward declarations for top-level class GraphicsOutputBase
 */
typedef GraphicsOutputBase GraphicsOutputBase_localtype;
Define_Module_ClassRef(panda3d.core, GraphicsOutputBase, GraphicsOutputBase_localtype, GraphicsOutputBase);
static struct Dtool_PyTypedObject *const Dtool_Ptr_GraphicsOutputBase = &Dtool_GraphicsOutputBase;
static void Dtool_PyModuleClassInit_GraphicsOutputBase(PyObject *module);

/**
 * Forward declarations for top-level class GraphicsStateGuardianBase
 */
typedef GraphicsStateGuardianBase GraphicsStateGuardianBase_localtype;
Define_Module_ClassRef(panda3d.core, GraphicsStateGuardianBase, GraphicsStateGuardianBase_localtype, GraphicsStateGuardianBase);
static struct Dtool_PyTypedObject *const Dtool_Ptr_GraphicsStateGuardianBase = &Dtool_GraphicsStateGuardianBase;
static void Dtool_PyModuleClassInit_GraphicsStateGuardianBase(PyObject *module);

/**
 * Declarations for exported classes
 */
static const Dtool_TypeDef exports[] = {
  {"GraphicsOutputBase", &Dtool_GraphicsOutputBase},
  {"GraphicsStateGuardianBase", &Dtool_GraphicsStateGuardianBase},
  {nullptr, nullptr},
};

/**
 * Extern declarations for imported classes
 */
#ifndef LINK_ALL_STATIC
static Dtool_TypeDef imports[] = {
  {"ReferenceCount", nullptr},
#define Dtool_Ptr_ReferenceCount (imports[0].type)
  {"TypeHandle", nullptr},
#define Dtool_Ptr_TypeHandle (imports[1].type)
  {"TypedObject", nullptr},
#define Dtool_Ptr_TypedObject (imports[2].type)
  {"TypedWritable", nullptr},
#define Dtool_Ptr_TypedWritable (imports[3].type)
  {"TypedWritableReferenceCount", nullptr},
#define Dtool_Ptr_TypedWritableReferenceCount (imports[4].type)
  {nullptr, nullptr},
};
#endif

// ReferenceCount
#ifndef LINK_ALL_STATIC
#else
extern struct Dtool_PyTypedObject Dtool_ReferenceCount;
static struct Dtool_PyTypedObject *const Dtool_Ptr_ReferenceCount = &Dtool_ReferenceCount;
#endif
// TypeHandle
#ifndef LINK_ALL_STATIC
inline static TypeHandle *Dtool_Coerce_TypeHandle(PyObject *args, TypeHandle &coerced) {
  nassertr(Dtool_Ptr_TypeHandle != nullptr, nullptr);
  nassertr(Dtool_Ptr_TypeHandle->_Dtool_Coerce != nullptr, nullptr);
  return ((TypeHandle *(*)(PyObject *, TypeHandle &))Dtool_Ptr_TypeHandle->_Dtool_Coerce)(args, coerced);
}
#else
extern struct Dtool_PyTypedObject Dtool_TypeHandle;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypeHandle = &Dtool_TypeHandle;
extern TypeHandle *Dtool_Coerce_TypeHandle(PyObject *args, TypeHandle &coerced);
#endif
// TypedObject
#ifndef LINK_ALL_STATIC
#else
extern struct Dtool_PyTypedObject Dtool_TypedObject;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypedObject = &Dtool_TypedObject;
#endif
// TypedWritable
#ifndef LINK_ALL_STATIC
#else
extern struct Dtool_PyTypedObject Dtool_TypedWritable;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypedWritable = &Dtool_TypedWritable;
#endif
// TypedWritableReferenceCount
#ifndef LINK_ALL_STATIC
#else
extern struct Dtool_PyTypedObject Dtool_TypedWritableReferenceCount;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypedWritableReferenceCount = &Dtool_TypedWritableReferenceCount;
#endif

/**
 * Python wrappers for global functions
 */
/**
 * Python wrappers for functions of class GraphicsOutputBase
 */
/**
 * Python function wrapper for:
 * virtual void GraphicsOutputBase::set_sort(int sort) = 0
 */
static PyObject *Dtool_GraphicsOutputBase_set_sort_3(PyObject *self, PyObject *arg) {
  GraphicsOutputBase *local_this = nullptr;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_GraphicsOutputBase, (void **)&local_this, "GraphicsOutputBase.set_sort")) {
    return nullptr;
  }
  // 1-virtual void GraphicsOutputBase::set_sort(int sort) = 0
  if (PyLongOrInt_Check(arg)) {
    long arg_val = PyLongOrInt_AS_LONG(arg);
#if (SIZEOF_LONG > SIZEOF_INT) && !defined(NDEBUG)
    if (arg_val < INT_MIN || arg_val > INT_MAX) {
      return PyErr_Format(PyExc_OverflowError,
                          "value %ld out of range for signed integer",
                          arg_val);
    }
#endif
    ((*local_this).set_sort)((int)arg_val);
    return Dtool_Return_None();
  }
  return Dtool_Raise_BadArgumentsError(
    "set_sort(const GraphicsOutputBase self, int sort)\n");
}

#ifndef NDEBUG
static const char *Dtool_GraphicsOutputBase_set_sort_3_comment =
  "C++ Interface:\n"
  "set_sort(const GraphicsOutputBase self, int sort)\n";
#else
static const char *Dtool_GraphicsOutputBase_set_sort_3_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static TypeHandle GraphicsOutputBase::get_class_type(void)
 */
static PyObject *Dtool_GraphicsOutputBase_get_class_type_5(PyObject *, PyObject *) {
  // 1-static TypeHandle GraphicsOutputBase::get_class_type(void)
  TypeHandle *return_value = new TypeHandle((GraphicsOutputBase::get_class_type)());
  if (return_value == nullptr) {
    return PyErr_NoMemory();
  }
  if (Dtool_CheckErrorOccurred()) {
    delete return_value;
    return nullptr;
  }
  return DTool_CreatePyInstance((void *)return_value, *Dtool_Ptr_TypeHandle, true, false);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsOutputBase_get_class_type_5_comment =
  "C++ Interface:\n"
  "get_class_type()\n";
#else
static const char *Dtool_GraphicsOutputBase_get_class_type_5_comment = nullptr;
#endif

static int Dtool_Init_GraphicsOutputBase(PyObject *self, PyObject *args, PyObject *kwds) {
  Dtool_Raise_TypeError("cannot init abstract class");
  return -1;
}

static void *Dtool_UpcastInterface_GraphicsOutputBase(PyObject *self, Dtool_PyTypedObject *requested_type) {
  Dtool_PyTypedObject *type = DtoolInstance_TYPE(self);
  if (type != &Dtool_GraphicsOutputBase) {
    printf("%s ** Bad Source Type-- Requesting Conversion from %s to %s\n", "GraphicsOutputBase", Py_TYPE(self)->tp_name, requested_type->_PyType.tp_name); fflush(nullptr);
    return nullptr;
  }

  GraphicsOutputBase *local_this = (GraphicsOutputBase *)DtoolInstance_VOID_PTR(self);
  if (requested_type == &Dtool_GraphicsOutputBase) {
    return local_this;
  }
  if (requested_type == Dtool_Ptr_ReferenceCount) {
    return (ReferenceCount *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedObject) {
    return (TypedObject *)(TypedWritable *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedWritable) {
    return (TypedWritable *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedWritableReferenceCount) {
    return (TypedWritableReferenceCount *) local_this;
  }
  return nullptr;
}

static PyObject *Dtool_Wrap_GraphicsOutputBase(void *from_this, PyTypeObject *from_type) {
  GraphicsOutputBase *to_this;
  if (from_type == nullptr || from_type == &Dtool_GraphicsOutputBase._PyType) {
    to_this = (GraphicsOutputBase *)from_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_ReferenceCount) {
    ReferenceCount *other_this = (ReferenceCount *)from_this;
    to_this = (GraphicsOutputBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedObject) {
    TypedObject *other_this = (TypedObject *)from_this;
    to_this = (GraphicsOutputBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedWritable) {
    TypedWritable *other_this = (TypedWritable *)from_this;
    to_this = (GraphicsOutputBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedWritableReferenceCount) {
    TypedWritableReferenceCount *other_this = (TypedWritableReferenceCount *)from_this;
    to_this = (GraphicsOutputBase *)other_this;
  }
  else {
    return nullptr;
  }
  // Allocate a new Python instance
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)PyType_GenericAlloc(&Dtool_GraphicsOutputBase._PyType, 0);
  self->_signature = PY_PANDA_SIGNATURE;
  self->_My_Type = &Dtool_GraphicsOutputBase;
  self->_ptr_to_object = to_this;
  self->_memory_rules = false;
  self->_is_const = false;
  return (PyObject *)self;
}

/**
 * Python wrappers for functions of class GraphicsStateGuardianBase
 */
/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_incomplete_render(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_incomplete_render_8(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_incomplete_render(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_incomplete_render)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_incomplete_render_8_comment =
  "C++ Interface:\n"
  "get_incomplete_render(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_incomplete_render_8_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_effective_incomplete_render(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_effective_incomplete_render(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_effective_incomplete_render)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9_comment =
  "C++ Interface:\n"
  "get_effective_incomplete_render(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::prefers_triangle_strips(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::prefers_triangle_strips(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).prefers_triangle_strips)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10_comment =
  "C++ Interface:\n"
  "prefers_triangle_strips(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual int GraphicsStateGuardianBase::get_max_vertices_per_array(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual int GraphicsStateGuardianBase::get_max_vertices_per_array(void) const = 0
  int return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_max_vertices_per_array)();
  if (Dtool_CheckErrorOccurred()) {
    return nullptr;
  }
  return Dtool_WrapValue(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11_comment =
  "C++ Interface:\n"
  "get_max_vertices_per_array(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual int GraphicsStateGuardianBase::get_max_vertices_per_primitive(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual int GraphicsStateGuardianBase::get_max_vertices_per_primitive(void) const = 0
  int return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_max_vertices_per_primitive)();
  if (Dtool_CheckErrorOccurred()) {
    return nullptr;
  }
  return Dtool_WrapValue(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12_comment =
  "C++ Interface:\n"
  "get_max_vertices_per_primitive(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual int GraphicsStateGuardianBase::get_max_texture_dimension(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual int GraphicsStateGuardianBase::get_max_texture_dimension(void) const = 0
  int return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_max_texture_dimension)();
  if (Dtool_CheckErrorOccurred()) {
    return nullptr;
  }
  return Dtool_WrapValue(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13_comment =
  "C++ Interface:\n"
  "get_max_texture_dimension(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_supports_compressed_texture_format(int compression_mode) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14(PyObject *self, PyObject *arg) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_supports_compressed_texture_format(int compression_mode) const = 0
  if (PyLongOrInt_Check(arg)) {
    long arg_val = PyLongOrInt_AS_LONG(arg);
#if (SIZEOF_LONG > SIZEOF_INT) && !defined(NDEBUG)
    if (arg_val < INT_MIN || arg_val > INT_MAX) {
      return PyErr_Format(PyExc_OverflowError,
                          "value %ld out of range for signed integer",
                          arg_val);
    }
#endif
    bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supports_compressed_texture_format)((int)arg_val);
    return Dtool_Return_Bool(return_value);
  }
  return Dtool_Raise_BadArgumentsError(
    "get_supports_compressed_texture_format(GraphicsStateGuardianBase self, int compression_mode)\n");
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14_comment =
  "C++ Interface:\n"
  "get_supports_compressed_texture_format(GraphicsStateGuardianBase self, int compression_mode)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_supports_multisample(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supports_multisample_15(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_supports_multisample(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supports_multisample)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supports_multisample_15_comment =
  "C++ Interface:\n"
  "get_supports_multisample(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supports_multisample_15_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual int GraphicsStateGuardianBase::get_supported_geom_rendering(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual int GraphicsStateGuardianBase::get_supported_geom_rendering(void) const = 0
  int return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supported_geom_rendering)();
  if (Dtool_CheckErrorOccurred()) {
    return nullptr;
  }
  return Dtool_WrapValue(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16_comment =
  "C++ Interface:\n"
  "get_supported_geom_rendering(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_supports_shadow_filter(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_supports_shadow_filter(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supports_shadow_filter)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17_comment =
  "C++ Interface:\n"
  "get_supports_shadow_filter(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_supports_texture_srgb(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_supports_texture_srgb(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supports_texture_srgb)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18_comment =
  "C++ Interface:\n"
  "get_supports_texture_srgb(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * virtual bool GraphicsStateGuardianBase::get_supports_hlsl(void) const = 0
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19(PyObject *self, PyObject *) {
  GraphicsStateGuardianBase *local_this = nullptr;
  if (!DtoolInstance_GetPointer(self, local_this, Dtool_GraphicsStateGuardianBase)) {
    return nullptr;
  }
  // 1-virtual bool GraphicsStateGuardianBase::get_supports_hlsl(void) const = 0
  bool return_value = ((*(const GraphicsStateGuardianBase*)local_this).get_supports_hlsl)();
  return Dtool_Return_Bool(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19_comment =
  "C++ Interface:\n"
  "get_supports_hlsl(GraphicsStateGuardianBase self)\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static GraphicsStateGuardianBase *GraphicsStateGuardianBase::get_default_gsg(void)
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_default_gsg_20(PyObject *, PyObject *) {
  // 1-static GraphicsStateGuardianBase *GraphicsStateGuardianBase::get_default_gsg(void)
  GraphicsStateGuardianBase *return_value = (GraphicsStateGuardianBase::get_default_gsg)();
  if (return_value != nullptr) {
    return_value->ref();
  }
  if (Dtool_CheckErrorOccurred()) {
    if (return_value != nullptr) {
      unref_delete(return_value);
    }
    return nullptr;
  }
  if (return_value == nullptr) {
    return Py_NewRef(Py_None);
  } else {
    return DTool_CreatePyInstanceTyped((void *)return_value, *Dtool_Ptr_GraphicsStateGuardianBase, true, false, return_value->as_typed_object()->get_type_index());
  }
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_default_gsg_20_comment =
  "C++ Interface:\n"
  "get_default_gsg()\n"
  "\n"
  "/**\n"
  " * Returns a pointer to the \"default\" GSG.  This is typically the first GSG\n"
  " * created in an application; in a single-window application, it will be the\n"
  " * only GSG. This GSG is used to determine default optimization choices for\n"
  " * loaded geometry.\n"
  " *\n"
  " * The return value may be NULL if a GSG has not been created.\n"
  " */";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_default_gsg_20_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static void GraphicsStateGuardianBase::set_default_gsg(GraphicsStateGuardianBase *default_gsg)
 */
static PyObject *Dtool_GraphicsStateGuardianBase_set_default_gsg_21(PyObject *, PyObject *arg) {
  // 1-static void GraphicsStateGuardianBase::set_default_gsg(GraphicsStateGuardianBase *default_gsg)
  GraphicsStateGuardianBase *arg_this = (GraphicsStateGuardianBase *)DTOOL_Call_GetPointerThisClass(arg, Dtool_Ptr_GraphicsStateGuardianBase, 0, "GraphicsStateGuardianBase.set_default_gsg", false, true);
  if (arg_this != nullptr) {
    (GraphicsStateGuardianBase::set_default_gsg)(arg_this);
    return Dtool_Return_None();
  }
  return Dtool_Raise_BadArgumentsError(
    "set_default_gsg(GraphicsStateGuardianBase default_gsg)\n");
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_set_default_gsg_21_comment =
  "C++ Interface:\n"
  "set_default_gsg(GraphicsStateGuardianBase default_gsg)\n"
  "\n"
  "/**\n"
  " * Specifies a particular GSG to use as the \"default\" GSG.  See\n"
  " * get_default_gsg().\n"
  " */";
#else
static const char *Dtool_GraphicsStateGuardianBase_set_default_gsg_21_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static std::size_t GraphicsStateGuardianBase::get_num_gsgs(void)
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_num_gsgs_22(PyObject *, PyObject *) {
  // 1-static std::size_t GraphicsStateGuardianBase::get_num_gsgs(void)
  std::size_t return_value = (GraphicsStateGuardianBase::get_num_gsgs)();
  if (Dtool_CheckErrorOccurred()) {
    return nullptr;
  }
  return Dtool_WrapValue(return_value);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_num_gsgs_22_comment =
  "C++ Interface:\n"
  "get_num_gsgs()\n"
  "\n"
  "/**\n"
  " * Returns the total number of GSG's in the universe.\n"
  " */";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_num_gsgs_22_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static GraphicsStateGuardianBase *GraphicsStateGuardianBase::get_gsg(std::size_t n)
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_gsg_23(PyObject *, PyObject *arg) {
  // 1-static GraphicsStateGuardianBase *GraphicsStateGuardianBase::get_gsg(std::size_t n)
  if (PyLongOrInt_Check(arg)) {
    size_t arg_val = PyLongOrInt_AsSize_t(arg);
#ifndef NDEBUG
    if (arg_val == (size_t)-1 && PyErr_Occurred()) {
      return nullptr;
    }
#endif
    GraphicsStateGuardianBase *return_value = (GraphicsStateGuardianBase::get_gsg)(arg_val);
    if (return_value != nullptr) {
      return_value->ref();
    }
    if (Dtool_CheckErrorOccurred()) {
      if (return_value != nullptr) {
        unref_delete(return_value);
      }
      return nullptr;
    }
    if (return_value == nullptr) {
      return Py_NewRef(Py_None);
    } else {
      return DTool_CreatePyInstanceTyped((void *)return_value, *Dtool_Ptr_GraphicsStateGuardianBase, true, false, return_value->as_typed_object()->get_type_index());
    }
  }
  return Dtool_Raise_BadArgumentsError(
    "get_gsg(int n)\n");
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_gsg_23_comment =
  "C++ Interface:\n"
  "get_gsg(int n)\n"
  "\n"
  "/**\n"
  " * Returns the nth GSG in the universe.  GSG's automatically add themselves\n"
  " * and remove themselves from this list as they are created and destroyed.\n"
  " */";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_gsg_23_comment = nullptr;
#endif

/**
 * Python function wrapper for:
 * static TypeHandle GraphicsStateGuardianBase::get_class_type(void)
 */
static PyObject *Dtool_GraphicsStateGuardianBase_get_class_type_25(PyObject *, PyObject *) {
  // 1-static TypeHandle GraphicsStateGuardianBase::get_class_type(void)
  TypeHandle *return_value = new TypeHandle((GraphicsStateGuardianBase::get_class_type)());
  if (return_value == nullptr) {
    return PyErr_NoMemory();
  }
  if (Dtool_CheckErrorOccurred()) {
    delete return_value;
    return nullptr;
  }
  return DTool_CreatePyInstance((void *)return_value, *Dtool_Ptr_TypeHandle, true, false);
}

#ifndef NDEBUG
static const char *Dtool_GraphicsStateGuardianBase_get_class_type_25_comment =
  "C++ Interface:\n"
  "get_class_type()\n";
#else
static const char *Dtool_GraphicsStateGuardianBase_get_class_type_25_comment = nullptr;
#endif

static int Dtool_Init_GraphicsStateGuardianBase(PyObject *self, PyObject *args, PyObject *kwds) {
  Dtool_Raise_TypeError("cannot init abstract class");
  return -1;
}

/*
 * Python make_seq wrapper
 */
static PyObject *MakeSeq_GraphicsStateGuardianBase_get_gsgs(PyObject *self, PyObject *) {
  Py_ssize_t count = (Py_ssize_t)(GraphicsStateGuardianBase::get_num_gsgs)();
  PyObject *tuple = PyTuple_New(count);

  for (Py_ssize_t i = 0; i < count; ++i) {
    PyObject *index = Dtool_WrapValue(i);
    PyObject *value = Dtool_GraphicsStateGuardianBase_get_gsg_23(self, index);
    PyTuple_SET_ITEM(tuple, i, value);
    Py_DECREF(index);
  }

  if (Dtool_CheckErrorOccurred()) {
    Py_DECREF(tuple);
    return nullptr;
  }
  return tuple;
}

static void *Dtool_UpcastInterface_GraphicsStateGuardianBase(PyObject *self, Dtool_PyTypedObject *requested_type) {
  Dtool_PyTypedObject *type = DtoolInstance_TYPE(self);
  if (type != &Dtool_GraphicsStateGuardianBase) {
    printf("%s ** Bad Source Type-- Requesting Conversion from %s to %s\n", "GraphicsStateGuardianBase", Py_TYPE(self)->tp_name, requested_type->_PyType.tp_name); fflush(nullptr);
    return nullptr;
  }

  GraphicsStateGuardianBase *local_this = (GraphicsStateGuardianBase *)DtoolInstance_VOID_PTR(self);
  if (requested_type == &Dtool_GraphicsStateGuardianBase) {
    return local_this;
  }
  if (requested_type == Dtool_Ptr_ReferenceCount) {
    return (ReferenceCount *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedObject) {
    return (TypedObject *)(TypedWritable *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedWritable) {
    return (TypedWritable *)(TypedWritableReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedWritableReferenceCount) {
    return (TypedWritableReferenceCount *) local_this;
  }
  return nullptr;
}

static PyObject *Dtool_Wrap_GraphicsStateGuardianBase(void *from_this, PyTypeObject *from_type) {
  GraphicsStateGuardianBase *to_this;
  if (from_type == nullptr || from_type == &Dtool_GraphicsStateGuardianBase._PyType) {
    to_this = (GraphicsStateGuardianBase *)from_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_ReferenceCount) {
    ReferenceCount *other_this = (ReferenceCount *)from_this;
    to_this = (GraphicsStateGuardianBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedObject) {
    TypedObject *other_this = (TypedObject *)from_this;
    to_this = (GraphicsStateGuardianBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedWritable) {
    TypedWritable *other_this = (TypedWritable *)from_this;
    to_this = (GraphicsStateGuardianBase *)other_this;
  }
  else if (from_type == (PyTypeObject *)Dtool_Ptr_TypedWritableReferenceCount) {
    TypedWritableReferenceCount *other_this = (TypedWritableReferenceCount *)from_this;
    to_this = (GraphicsStateGuardianBase *)other_this;
  }
  else {
    return nullptr;
  }
  // Allocate a new Python instance
  Dtool_PyInstDef *self = (Dtool_PyInstDef *)PyType_GenericAlloc(&Dtool_GraphicsStateGuardianBase._PyType, 0);
  self->_signature = PY_PANDA_SIGNATURE;
  self->_My_Type = &Dtool_GraphicsStateGuardianBase;
  self->_ptr_to_object = to_this;
  self->_memory_rules = false;
  self->_is_const = false;
  return (PyObject *)self;
}

/**
 * Python method tables for GraphicsOutputBase (GraphicsOutputBase)
 */
static PyMethodDef Dtool_Methods_GraphicsOutputBase[] = {
  {"set_sort", &Dtool_GraphicsOutputBase_set_sort_3, METH_O, (const char *)Dtool_GraphicsOutputBase_set_sort_3_comment},
  {"setSort", &Dtool_GraphicsOutputBase_set_sort_3, METH_O, (const char *)Dtool_GraphicsOutputBase_set_sort_3_comment},
  {"get_class_type", &Dtool_GraphicsOutputBase_get_class_type_5, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsOutputBase_get_class_type_5_comment},
  {"getClassType", &Dtool_GraphicsOutputBase_get_class_type_5, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsOutputBase_get_class_type_5_comment},
  {nullptr, nullptr, 0, nullptr}
};

static PyNumberMethods Dtool_NumberMethods_GraphicsOutputBase = {
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr, // nb_long
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#if PY_VERSION_HEX >= 0x02050000
  nullptr,
#endif
#if PY_VERSION_HEX >= 0x03050000
  nullptr,
  nullptr,
#endif
};

static PySequenceMethods Dtool_SequenceMethods_GraphicsOutputBase = {
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr, // sq_slice
  nullptr,
  nullptr, // sq_ass_slice
  nullptr,
  nullptr,
  nullptr,
};

static PyMappingMethods Dtool_MappingMethods_GraphicsOutputBase = {
  nullptr,
  nullptr,
  nullptr,
};

static PyBufferProcs Dtool_BufferProcs_GraphicsOutputBase = {
#if PY_MAJOR_VERSION < 3
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#endif
#if PY_VERSION_HEX >= 0x02060000
  nullptr,
  nullptr,
#endif
};

#if PY_VERSION_HEX >= 0x03050000
static PyAsyncMethods Dtool_AsyncMethods_GraphicsOutputBase = {
  nullptr,
  nullptr,
  nullptr,
};
#endif

struct Dtool_PyTypedObject Dtool_GraphicsOutputBase = {
  {
    PyVarObject_HEAD_INIT(nullptr, 0)
    "panda3d.core.GraphicsOutputBase",
    0, // tp_basicsize
    0, // tp_itemsize
    &Dtool_FreeInstance_GraphicsOutputBase,
#if PY_VERSION_HEX >= 0x03080000
    0, // tp_vectorcall_offset
#else
    nullptr,
#endif
    nullptr,
    nullptr,
#if PY_VERSION_HEX >= 0x03050000
    &Dtool_AsyncMethods_GraphicsOutputBase,
#elif PY_MAJOR_VERSION >= 3
    nullptr, // tp_reserved
#else
    nullptr, // tp_compare
#endif
    nullptr,
    &Dtool_NumberMethods_GraphicsOutputBase,
    &Dtool_SequenceMethods_GraphicsOutputBase,
    &Dtool_MappingMethods_GraphicsOutputBase,
    nullptr, // tp_hash
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    &Dtool_BufferProcs_GraphicsOutputBase,
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES,
#ifdef NDEBUG
    0,
#else
    "/**\n"
    " * An abstract base class for GraphicsOutput, for all the usual reasons.\n"
    " */",
#endif
    nullptr, // tp_traverse
    nullptr, // tp_clear
    nullptr, // tp_richcompare
    0, // tp_weaklistoffset
    nullptr,
    nullptr,
    Dtool_Methods_GraphicsOutputBase,
    nullptr, // tp_members
    nullptr, // tp_getset
    nullptr, // tp_base
    nullptr, // tp_dict
    nullptr,
    nullptr,
    0, // tp_dictoffset
    Dtool_Init_GraphicsOutputBase,
    PyType_GenericAlloc,
    Dtool_new_GraphicsOutputBase,
    PyObject_Del,
    nullptr, // tp_is_gc
    nullptr, // tp_bases
    nullptr, // tp_mro
    nullptr, // tp_cache
    nullptr, // tp_subclasses
    nullptr, // tp_weaklist
    nullptr, // tp_del
#if PY_VERSION_HEX >= 0x02060000
    0, // tp_version_tag
#endif
#if PY_VERSION_HEX >= 0x03040000
    nullptr, // tp_finalize
#endif
#if PY_VERSION_HEX >= 0x03080000
    nullptr, // tp_vectorcall
#endif
  },
  TypeHandle::none(),
  Dtool_PyModuleClassInit_GraphicsOutputBase,
  Dtool_UpcastInterface_GraphicsOutputBase,
  Dtool_Wrap_GraphicsOutputBase,
  nullptr,
  nullptr,
};

static void Dtool_PyModuleClassInit_GraphicsOutputBase(PyObject *module) {
  (void) module; // Unused
  static bool initdone = false;
  if (!initdone) {
    // Dependent objects
    assert(Dtool_Ptr_TypedWritableReferenceCount != nullptr);
    assert(Dtool_Ptr_TypedWritableReferenceCount->_Dtool_ModuleClassInit != nullptr);
    Dtool_Ptr_TypedWritableReferenceCount->_Dtool_ModuleClassInit(nullptr);
    if (initdone) {
      return;
    }
    initdone = true;
    Dtool_GraphicsOutputBase._PyType.tp_bases = PyTuple_Pack(1, (PyTypeObject *)Dtool_Ptr_TypedWritableReferenceCount);
    Dtool_GraphicsOutputBase._PyType.tp_base = (PyTypeObject *)Dtool_GetSuperBase();
    PyObject *dict = PyDict_New();
    Dtool_GraphicsOutputBase._PyType.tp_dict = dict;
    PyDict_SetItemString(dict, "DtoolClassDict", dict);
    if (PyType_Ready((PyTypeObject *)&Dtool_GraphicsOutputBase) < 0) {
      PyErr_Print();
      PyErr_Format(PyExc_TypeError, "PyType_Ready(%s)", "GraphicsOutputBase");
      return;
    }
    Py_INCREF((PyTypeObject *)&Dtool_GraphicsOutputBase);
  }
}

/**
 * Python method tables for GraphicsStateGuardianBase (GraphicsStateGuardianBase)
 */
static PyMethodDef Dtool_Methods_GraphicsStateGuardianBase[] = {
  {"get_incomplete_render", &Dtool_GraphicsStateGuardianBase_get_incomplete_render_8, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_incomplete_render_8_comment},
  {"getIncompleteRender", &Dtool_GraphicsStateGuardianBase_get_incomplete_render_8, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_incomplete_render_8_comment},
  {"get_effective_incomplete_render", &Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9_comment},
  {"getEffectiveIncompleteRender", &Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_effective_incomplete_render_9_comment},
  {"prefers_triangle_strips", &Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10_comment},
  {"prefersTriangleStrips", &Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_prefers_triangle_strips_10_comment},
  {"get_max_vertices_per_array", &Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11_comment},
  {"getMaxVerticesPerArray", &Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_vertices_per_array_11_comment},
  {"get_max_vertices_per_primitive", &Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12_comment},
  {"getMaxVerticesPerPrimitive", &Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_vertices_per_primitive_12_comment},
  {"get_max_texture_dimension", &Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13_comment},
  {"getMaxTextureDimension", &Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_max_texture_dimension_13_comment},
  {"get_supports_compressed_texture_format", &Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14, METH_O, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14_comment},
  {"getSupportsCompressedTextureFormat", &Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14, METH_O, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_compressed_texture_format_14_comment},
  {"get_supports_multisample", &Dtool_GraphicsStateGuardianBase_get_supports_multisample_15, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_multisample_15_comment},
  {"getSupportsMultisample", &Dtool_GraphicsStateGuardianBase_get_supports_multisample_15, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_multisample_15_comment},
  {"get_supported_geom_rendering", &Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16_comment},
  {"getSupportedGeomRendering", &Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supported_geom_rendering_16_comment},
  {"get_supports_shadow_filter", &Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17_comment},
  {"getSupportsShadowFilter", &Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_shadow_filter_17_comment},
  {"get_supports_texture_srgb", &Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18_comment},
  {"getSupportsTextureSrgb", &Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_texture_srgb_18_comment},
  {"get_supports_hlsl", &Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19_comment},
  {"getSupportsHlsl", &Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19, METH_NOARGS, (const char *)Dtool_GraphicsStateGuardianBase_get_supports_hlsl_19_comment},
  {"get_default_gsg", &Dtool_GraphicsStateGuardianBase_get_default_gsg_20, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_default_gsg_20_comment},
  {"getDefaultGsg", &Dtool_GraphicsStateGuardianBase_get_default_gsg_20, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_default_gsg_20_comment},
  {"set_default_gsg", &Dtool_GraphicsStateGuardianBase_set_default_gsg_21, METH_O | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_set_default_gsg_21_comment},
  {"setDefaultGsg", &Dtool_GraphicsStateGuardianBase_set_default_gsg_21, METH_O | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_set_default_gsg_21_comment},
  {"get_num_gsgs", &Dtool_GraphicsStateGuardianBase_get_num_gsgs_22, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_num_gsgs_22_comment},
  {"getNumGsgs", &Dtool_GraphicsStateGuardianBase_get_num_gsgs_22, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_num_gsgs_22_comment},
  {"get_gsg", &Dtool_GraphicsStateGuardianBase_get_gsg_23, METH_O | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_gsg_23_comment},
  {"getGsg", &Dtool_GraphicsStateGuardianBase_get_gsg_23, METH_O | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_gsg_23_comment},
  {"get_class_type", &Dtool_GraphicsStateGuardianBase_get_class_type_25, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_class_type_25_comment},
  {"getClassType", &Dtool_GraphicsStateGuardianBase_get_class_type_25, METH_NOARGS | METH_STATIC, (const char *)Dtool_GraphicsStateGuardianBase_get_class_type_25_comment},
  {"get_gsgs", (PyCFunction) &MakeSeq_GraphicsStateGuardianBase_get_gsgs, METH_NOARGS | METH_STATIC, nullptr},
  { "getGsgs", (PyCFunction) &MakeSeq_GraphicsStateGuardianBase_get_gsgs, METH_NOARGS | METH_STATIC, nullptr},
  {nullptr, nullptr, 0, nullptr}
};

static PyNumberMethods Dtool_NumberMethods_GraphicsStateGuardianBase = {
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr, // nb_long
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
#if PY_MAJOR_VERSION < 3
  nullptr,
#endif
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#if PY_VERSION_HEX >= 0x02050000
  nullptr,
#endif
#if PY_VERSION_HEX >= 0x03050000
  nullptr,
  nullptr,
#endif
};

static PySequenceMethods Dtool_SequenceMethods_GraphicsStateGuardianBase = {
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  nullptr, // sq_slice
  nullptr,
  nullptr, // sq_ass_slice
  nullptr,
  nullptr,
  nullptr,
};

static PyMappingMethods Dtool_MappingMethods_GraphicsStateGuardianBase = {
  nullptr,
  nullptr,
  nullptr,
};

static PyBufferProcs Dtool_BufferProcs_GraphicsStateGuardianBase = {
#if PY_MAJOR_VERSION < 3
  nullptr,
  nullptr,
  nullptr,
  nullptr,
#endif
#if PY_VERSION_HEX >= 0x02060000
  nullptr,
  nullptr,
#endif
};

#if PY_VERSION_HEX >= 0x03050000
static PyAsyncMethods Dtool_AsyncMethods_GraphicsStateGuardianBase = {
  nullptr,
  nullptr,
  nullptr,
};
#endif

struct Dtool_PyTypedObject Dtool_GraphicsStateGuardianBase = {
  {
    PyVarObject_HEAD_INIT(nullptr, 0)
    "panda3d.core.GraphicsStateGuardianBase",
    0, // tp_basicsize
    0, // tp_itemsize
    &Dtool_FreeInstance_GraphicsStateGuardianBase,
#if PY_VERSION_HEX >= 0x03080000
    0, // tp_vectorcall_offset
#else
    nullptr,
#endif
    nullptr,
    nullptr,
#if PY_VERSION_HEX >= 0x03050000
    &Dtool_AsyncMethods_GraphicsStateGuardianBase,
#elif PY_MAJOR_VERSION >= 3
    nullptr, // tp_reserved
#else
    nullptr, // tp_compare
#endif
    nullptr,
    &Dtool_NumberMethods_GraphicsStateGuardianBase,
    &Dtool_SequenceMethods_GraphicsStateGuardianBase,
    &Dtool_MappingMethods_GraphicsStateGuardianBase,
    nullptr, // tp_hash
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    &Dtool_BufferProcs_GraphicsStateGuardianBase,
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES,
#ifdef NDEBUG
    0,
#else
    "/**\n"
    " * This is a base class for the GraphicsStateGuardian class, which is itself a\n"
    " * base class for the various GSG's for different platforms.  This class\n"
    " * contains all the function prototypes to support the double-dispatch of GSG\n"
    " * to geoms, transitions, etc.  It lives in a separate class in its own\n"
    " * package so we can avoid circular build dependency problems.\n"
    " *\n"
    " * GraphicsStateGuardians are not actually writable to bam files, of course,\n"
    " * but they may be passed as event parameters, so they inherit from\n"
    " * TypedWritableReferenceCount instead of TypedReferenceCount for that\n"
    " * convenience.\n"
    " */",
#endif
    nullptr, // tp_traverse
    nullptr, // tp_clear
    nullptr, // tp_richcompare
    0, // tp_weaklistoffset
    nullptr,
    nullptr,
    Dtool_Methods_GraphicsStateGuardianBase,
    nullptr, // tp_members
    nullptr, // tp_getset
    nullptr, // tp_base
    nullptr, // tp_dict
    nullptr,
    nullptr,
    0, // tp_dictoffset
    Dtool_Init_GraphicsStateGuardianBase,
    PyType_GenericAlloc,
    Dtool_new_GraphicsStateGuardianBase,
    PyObject_Del,
    nullptr, // tp_is_gc
    nullptr, // tp_bases
    nullptr, // tp_mro
    nullptr, // tp_cache
    nullptr, // tp_subclasses
    nullptr, // tp_weaklist
    nullptr, // tp_del
#if PY_VERSION_HEX >= 0x02060000
    0, // tp_version_tag
#endif
#if PY_VERSION_HEX >= 0x03040000
    nullptr, // tp_finalize
#endif
#if PY_VERSION_HEX >= 0x03080000
    nullptr, // tp_vectorcall
#endif
  },
  TypeHandle::none(),
  Dtool_PyModuleClassInit_GraphicsStateGuardianBase,
  Dtool_UpcastInterface_GraphicsStateGuardianBase,
  Dtool_Wrap_GraphicsStateGuardianBase,
  nullptr,
  nullptr,
};

static void Dtool_PyModuleClassInit_GraphicsStateGuardianBase(PyObject *module) {
  (void) module; // Unused
  static bool initdone = false;
  if (!initdone) {
    // Dependent objects
    assert(Dtool_Ptr_TypedWritableReferenceCount != nullptr);
    assert(Dtool_Ptr_TypedWritableReferenceCount->_Dtool_ModuleClassInit != nullptr);
    Dtool_Ptr_TypedWritableReferenceCount->_Dtool_ModuleClassInit(nullptr);
    if (initdone) {
      return;
    }
    initdone = true;
    Dtool_GraphicsStateGuardianBase._PyType.tp_bases = PyTuple_Pack(1, (PyTypeObject *)Dtool_Ptr_TypedWritableReferenceCount);
    Dtool_GraphicsStateGuardianBase._PyType.tp_base = (PyTypeObject *)Dtool_GetSuperBase();
    PyObject *dict = PyDict_New();
    Dtool_GraphicsStateGuardianBase._PyType.tp_dict = dict;
    PyDict_SetItemString(dict, "DtoolClassDict", dict);
    if (PyType_Ready((PyTypeObject *)&Dtool_GraphicsStateGuardianBase) < 0) {
      PyErr_Print();
      PyErr_Format(PyExc_TypeError, "PyType_Ready(%s)", "GraphicsStateGuardianBase");
      return;
    }
    Py_INCREF((PyTypeObject *)&Dtool_GraphicsStateGuardianBase);
  }
}


/**
 * Module Object Linker ..
 */
void Dtool_libp3gsgbase_RegisterTypes() {
  TypeRegistry *registry = TypeRegistry::ptr();
  nassertv(registry != nullptr);
  {
    GraphicsOutputBase::init_type();
    TypeHandle handle = GraphicsOutputBase::get_class_type();
    Dtool_GraphicsOutputBase._type = handle;
    registry->record_python_type(handle, &Dtool_GraphicsOutputBase._PyType, Dtool_Wrap_GraphicsOutputBase);
  }
  {
    GraphicsStateGuardianBase::init_type();
    TypeHandle handle = GraphicsStateGuardianBase::get_class_type();
    Dtool_GraphicsStateGuardianBase._type = handle;
    registry->record_python_type(handle, &Dtool_GraphicsStateGuardianBase._PyType, Dtool_Wrap_GraphicsStateGuardianBase);
  }
}

void Dtool_libp3gsgbase_BuildInstants(PyObject *module) {
  (void) module;
  // GraphicsOutputBase
  Dtool_PyModuleClassInit_GraphicsOutputBase(module);
  PyModule_AddObject(module, "GraphicsOutputBase", (PyObject *)&Dtool_GraphicsOutputBase);
  // GraphicsStateGuardianBase
  Dtool_PyModuleClassInit_GraphicsStateGuardianBase(module);
  PyModule_AddObject(module, "GraphicsStateGuardianBase", (PyObject *)&Dtool_GraphicsStateGuardianBase);
}

static PyMethodDef python_simple_funcs[] = {
  // Support Function For Dtool_types ... for now in each module ??
  {"Dtool_BorrowThisReference", &Dtool_BorrowThisReference, METH_VARARGS, "Used to borrow 'this' pointer (to, from)\nAssumes no ownership."},
  {nullptr, nullptr, 0, nullptr}
};

static const InterrogateModuleDef _in_module_def = {
  1775484313,  /* file_identifier */
  "libp3gsgbase",  /* library_name */
  "Oe1b",  /* library_hash_name */
  "panda3d.core",  /* module_name */
  "libp3gsgbase.in",  /* database_filename */
  nullptr,  /* unique_names */
  0,  /* num_unique_names */
  nullptr,  /* fptrs */
  0,  /* num_fptrs */
  1,  /* first_index */
  62  /* next_index */
};

#ifdef LINK_ALL_STATIC
extern const struct LibraryDef libp3gsgbase_moddef = {python_simple_funcs, exports, nullptr, &_in_module_def};
#else
extern const struct LibraryDef libp3gsgbase_moddef = {python_simple_funcs, exports, imports, &_in_module_def};
#endif
