/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file navPath.h
 * @author Ashwani / 
 * @date 2024
 */

#ifndef NAVPATH_H
#define NAVPATH_H

#include "pandabase.h"
#include "config_navmesh.h" // Added config include
#include "typedReferenceCount.h"
#include "luse.h"
#include "pvector.h"

/**
 * This class represents a path generated by the NavMesh.
 * It contains a sequence of waypoints.
 */
class EXPCL_PANDA_NAVMESH NavPath : public TypedReferenceCount {
PUBLISHED:
  NavPath();
  ~NavPath();

  // Returns the number of points in the path.
  INLINE int get_num_points() const;
  
  // Returns the point at the given index.
  INLINE LPoint3 get_point(int i) const;
  
  // Returns the total length of the path.
  PN_stdfloat get_length() const;

public:
  // Internal method to add points
  void add_point(const LPoint3 &point);

private:
  pvector<LPoint3> _waypoints;

public:
  static TypeHandle get_class_type() {
    return _type_handle;
  }
  static void init_type() {
    TypedReferenceCount::init_type();
    register_type(_type_handle, "NavPath",
                  TypedReferenceCount::get_class_type());
  }
  virtual TypeHandle get_type() const {
    return get_class_type();
  }
  virtual TypeHandle force_init_type() {init_type(); return get_class_type();}

private:
  static TypeHandle _type_handle;
};

#include "navPath.I"

#endif // NAVPATH_H
