#define PANDA_VERSION_MAJOR                0
#define PANDA_VERSION_MINOR                0
#define PANDA_VERSION_BUILDSUBVERSION      0
#define PANDA_VERSION_BUILDSUBSUBVERSION   1

#define PANDA_VERSION_MAJOR_STR                "0"
#define PANDA_VERSION_MINOR_STR                "0"
#define PANDA_VERSION_BUILDSUBVERSION_STR      "0"
#define PANDA_VERSION_BUILDSUBSUBVERSION_STR   "1"

