#! /bin/sh

# This is just a helper script to generatePythonCode to cover
# the three or four cases we use all the time
# usage: genPyCode [-t] win-[linux/win-debug/win-release/win-publish] [other libs]
# -t adds libtoontown

firstarg="$1"
extra_genPyCode_libs=""
fSqueeze="squeezeMe"
optimizeFlag=""
ppythonOptimizeFlag=""

if [ "$firstarg" = "-t" ]; then
extra_genPyCode_libs="$extra_genPyCode_libs libtoontown"
shift
firstarg="$1"
fi

if [ "$firstarg" = "-b" ]; then
extra_genPyCode_libs="$extra_genPyCode_libs libbartop"
shift
firstarg="$1"
fi

if [ "$firstarg" = "-tt" ]; then
extra_genPyCode_libs="$extra_genPyCode_libs libttrader"
shift
firstarg="$1"
fi

if [ "$firstarg" = "-v" ]; then
extra_genPyCode_libs="$extra_genPyCode_libs libvrpn"
shift
firstarg="$1"
fi

if [ "$firstarg" = "-ns" ]; then
fSqueeze=""
shift
firstarg="$1"
fi

shift
extra_genPyCode_libs="$extra_genPyCode_libs $*"

if [ "$firstarg" = "linux" ]; then
    cd $DIRECT/bin
    ppython -d generatePythonCode -v -d $DIRECT/lib/py -e $DIRECT/src/extensions -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
fi

if [ "$firstarg" = "win-debug" ]; then
    cd $DIRECT/bin
    ppython -d generatePythonCode -v -d `cygpath -w $DIRECT/lib/py` -e `cygpath -w $DIRECT/src/extensions` -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
fi

if [ "$firstarg" = "win-release" ]; then
    cd $DIRECT/bin
    ppython generatePythonCode -v -d `cygpath -w $DIRECT/lib/py` -e `cygpath -w $DIRECT/src/extensions` -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
fi

if [ "$firstarg" = "win-publish" ]; then
    # no assertions, no comments, no docstrings
    cd $DIRECT/bin
    ppython -OO generatePythonCode -O -v -d `cygpath -w $DIRECT/lib/py` -e `cygpath -w $DIRECT/src/extensions` -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
    optimizeFlag="-O"
    ppythonOptimizeFlag="-OO"
fi

if [ "$firstarg" = "install" ]; then
    # as installed on a machine without ctattach etc.
    install/bin/ppython -d install/bin/generatePythonCode -O -v -d install/lib/py -e direct/src/extensions -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
fi

if [ "$firstarg" = "release" ]; then
    # as installed on a machine without ctattach etc.
    install/bin/ppython install/bin/generatePythonCode -v -d install/lib/py -e direct/src/extensions -i libdtoolconfig libpandaexpress libpanda libpandaphysics libdirect $extra_genPyCode_libs || exit
fi

if [ "$fSqueeze" = "squeezeMe" ]; then
    echo SQUEEZING PandaModules
    cd $DIRECT/lib/py
    rm -f PandaModules.py*
    pSqueezer=`cygpath -w $DIRECT/src/showbase/pandaSqueezer.py`
    ppython $ppythonOptimizeFlag $pSqueezer $optimizeFlag || exit
else
    echo RENAMING PandaModulesUnsqueezed.py to PandaModules.py
    cd $DIRECT/lib/py
    rm -f PandaModules.py*
    mv PandaModulesUnsqueezed.py PandaModules.py
fi

echo DONE

