/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file datagramSink.I
 * @author jason
 * @date 2000-06-07
 */

/**
 * Does nothing since this is class is just the definition of an interface
 */

INLINE DatagramSink::DatagramSink(){
}
