/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file physxJointDesc.I
 * @author enn0x
 * @date 2009-09-28
 */

////////////////////////////////////////////////////////////////////
//     Function: PhysxJointDesc::Constructor
//       Access: Protected
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxJointDesc::
PhysxJointDesc() {

}

////////////////////////////////////////////////////////////////////
//     Function: PhysxJointDesc::Destructor
//       Access: Protected
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxJointDesc::
~PhysxJointDesc() {

}

