// Filename: physxCylindricalJoint.I
// Created by:  enn0x (02Oct09)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) Carnegie Mellon University.  All rights reserved.
//
// All use of this software is subject to the terms of the revised BSD
// license.  You should have received a copy of this license along
// with this source code in a file named "LICENSE."
//
////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////
//     Function: PhysxCylindricalJoint::Constructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxCylindricalJoint::
PhysxCylindricalJoint() : PhysxJoint() {

}

////////////////////////////////////////////////////////////////////
//     Function: PhysxCylindricalJoint::Destructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxCylindricalJoint::
~PhysxCylindricalJoint() {

}

