// Filename: physxHeightFieldShape.I
// Created by:  enn0x (15Oct09)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) Carnegie Mellon University.  All rights reserved.
//
// All use of this software is subject to the terms of the revised BSD
// license.  You should have received a copy of this license along
// with this source code in a file named "LICENSE."
//
////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////
//     Function: PhysxHeightFieldShape::Constructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxHeightFieldShape::
PhysxHeightFieldShape() : PhysxShape() {

}

////////////////////////////////////////////////////////////////////
//     Function: PhysxHeightFieldShape::Destructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxHeightFieldShape::
~PhysxHeightFieldShape() {

}

