#include "collisionHandlerEvent_ext.cxx"
#include "collisionHandlerPhysical_ext.cxx"
#include "collisionHandlerQueue_ext.cxx"
#include "collisionNode_ext.cxx"
#include "collisionPolygon_ext.cxx"
#include "collisionTraverser_ext.cxx"
