class IMoniker;
class IMediaSample;
class IMemAllocator;
class IMediaControl;
class IMemInputPin;
class IGraphBuilder;
class ICaptureGraphBuilder2;
class IBaseFilter;
class IAMStreamConfig;
template <class T> class CComPtr;
