
cmu:
	python makepanda/makepanda.py --default

vrstudio:
	python -u makepanda/makepanda.py --prefix=../built --verbose --everything --no-fmod --no-helix --no-maya5 --no-max5 --no-max6 --no-max7 --use-miles --thirdparty=../thirdparty/win-libs-vc7/ --directx-sdk=C:/cygwin/home/skyler/player/wintools/sdk/DirectX/

lean:
	python -u makepanda/makepanda.py --prefix=../built --nothing --thirdparty=../thirdparty/win-libs-vc7/ --directx-sdk=C:/cygwin/home/skyler/player/wintools/sdk/DirectX/

vr:
	python -u makepanda/build.py

#--thirdparty=../thirdparty/win-libs-vc7/ --directx-sdk=$WINTOOLS/sdk/DirectX/
