
cmu:
	python makepanda/makepanda.py --default

vrstudio:
	python makepanda/makepanda.py --default --no-installer --no-fmod --no-maya5 --no-max5 --no-max6 --no-max7 --miles --thirdparty=../thirdparty/win-libs-vc7/
