#! /bin/csh -f
#
# Automatically generate a header file for $1
#
if ( ${#argv} < 1 ) then
	echo You need to specify a filename... ala test.{c++,C,h,sal,ss}
	exit 1
	endif

# Let's do it

# flags
set hfile=0
set cfile=0
set cppfile=0
set salfile=0

if ( `basename $1 .h` != $1 ) set hfile=1
if ( `basename $1 .hh` != $1 ) set hfile=1
if ( `basename $1 .c` != $1 ) set cfile=1
if ( `basename $1 .c++` != $1 ) set cppfile=1
if ( `basename $1 .cxx` != $1 ) set cppfile=1
if ( `basename $1 .cc` != $1 ) set cppfile=1
if ( `basename $1 .C` != $1 ) set cppfile=1
if ( `basename $1 .I` != $1 ) set cppfile=1
if ( `basename $1 .i` != $1 ) set cppfile=1
if ( `basename $1 .ii` != $1 ) set cppfile=1
if ( `basename $1 .sal` != $1 ) set salfile=1
if ( `basename $1 .ss` != $1 ) set salfile=1
if ( `basename $1 .el` != $1 ) set salfile=1
if ( `basename $1 .stk` != $1 ) set salfile=1

if ( ! ( $hfile || $cfile || $cppfile || $salfile ) ) then
 echo Usage: $0 filename.ext
 echo where ext is one of .h .hh .c .c++ .cxx .cc .C .sal .ss .el or .stk
 exit 1
endif

# echo $hfile $cppfile $salfile 
if ( $hfile || $cppfile ) then
    
    cat <<END_OF_PROTO
// Filename: $1
// Created by:  `whoami` (`/bin/date '+%d%b%y'`)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) 2001 - 2004, Disney Enterprises, Inc.  All rights reserved
//
// All use of this software is subject to the terms of the Panda 3d
// Software license.  You should have received a copy of this license
// along with this source code; you will also find a current copy of
// the license at http://etc.cmu.edu/panda3d/docs/license/ .
//
// To contact the maintainers of this program write to
// panda3d-general@lists.sourceforge.net .
//
////////////////////////////////////////////////////////////////////
END_OF_PROTO

else if ( $cfile ) then
    
    cat <<END_OF_PROTO
/* Filename: $1
 * Created by:  `whoami` (`/bin/date '+%d%b%y'`)
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * PANDA 3D SOFTWARE
 * Copyright (c) 2001 - 2004, Disney Enterprises, Inc.  All rights reserved
 *
 * All use of this software is subject to the terms of the Panda 3d
 * Software license.  You should have received a copy of this license
 * along with this source code; you will also find a current copy of
 * the license at http://etc.cmu.edu/panda3d/docs/license/ .
 *
 * To contact the maintainers of this program write to
 * panda3d-general@lists.sourceforge.net .
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
END_OF_PROTO

else
#
# Scheme
#
cat <<END_OF_PROTO
;; Filename: $1
;; Created by:  `whoami` (`/bin/date '+%d%b%y'`)
;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;

;;;*Description

;;;.

;;;*Public

;;;*Private
END_OF_PROTO
endif

echo

