#!/usr/local/bin/perl

sub CTCoUsage {
    print STDERR "Usage: ctco [-c \"comment\"] [-nc] element-name [...]\n" ;
    print STDERR "Options:\n" ;
    print STDERR "  -c \"comment\" : provide a comment about this action\n" ;
    print STDERR "  -nc : expect no comment on this action\n" ;
    exit;
}

if ( $#ARGV < 0 ) {
    &CTCoUsage ;
}

$tool = $ENV{"DTOOL"} ;
if ( $tool eq "" ) {
   die "Environment not configured for CTtools" ;
}

require "$tool/inc/ctutils.pl" ;
require "$tool/inc/ctvspec.pl" ;
require "$tool/inc/ctquery.pl" ;
require "$tool/inc/ctproj.pl" ;
require "$tool/inc/ctcm.pl" ;

$comment = "" ;
if ( $ARGV[0] eq "-nc" ) {
    shift( @ARGV ) ;
    &CTUDebug( "-nc processed\n" ) ;
}
if ( $ARGV[0] eq "-c" ) {
    shift( @ARGV ) ;
    $comment = $ARGV[0] ;
    shift( @ARGV ) ;
    &CTUDebug( "setting comment to '" . $comment . "'\n" ) ;
}

if ( $#ARGV < 0 ) {
    &CTCoUsage ;
}

$projname = &CTProj ;
$projname =~ tr/A-Z/a-z/ ;
$flav = &CTQueryProj( $projname ) ;
$spec = &CTResolveSpec( $projname, $flav ) ;

foreach $item ( @ARGV ) {
    if ( -e $item ) {
	if ( ! &CTCMCheckout( $item, $projname, $spec, $comment ) ) {
	    print STDERR "Could not checkout '$item'\n" ;
	}
    } else {
	print STDERR "No such file '$item'.\n" ;
    }
}
