#!/usr/local/bin/perl

if ($#ARGV < 0) {
   exit print "Usage: ctdelta element-name [...]\n" ;
}

$tool = $ENV{"DTOOL"} ;
if ( $tool eq "" ) {
    die "not configured for using ct-tools\n" ;
}

require "$tool/inc/ctutils.pl" ;
require "$tool/inc/ctvspec.pl" ;
require "$tool/inc/ctquery.pl" ;
require "$tool/inc/ctproj.pl" ;
require "$tool/inc/ctcm.pl" ;

$projname = &CTProj ;
$projname =~ tr/A-Z/a-z/ ;
$flav = &CTQueryProj( $projname ) ;
$spec = &CTResolveSpec( $projname, $flav ) ;

foreach $item ( @ARGV ) {
    if ( -e $item ) {
	&CTCMCheckin( $item, $projname, $spec ) ;
	if ( ! &CTCMDelta( $item, $projname, $spec ) ) {
	    print STDERR "Could not delta '$item'\n" ;
	}
    } else {
	print STDERR "No such file '$item'.\n" ;
    }
}
