#!/usr/bin/perl

$tool = $ENV{"DTOOL"} ;
if ( $tool eq "" ) {
    die "not configured for using ct-tools\n" ;
}

require "$tool/built/include/ctutils.pl" ;
require "$tool/built/include/ctvspec.pl" ;
require "$tool/built/include/ctquery.pl" ;
require "$tool/built/include/ctproj.pl" ;
require "$tool/built/include/ctcm.pl" ;

$projname = &CTProj ;
$projname =~ tr/A-Z/a-z/ ;
$flav = &CTQueryProj( $projname ) ;
$spec = &CTResolveSpec( $projname, $flav ) ;

$line = join( " ", @ARGV ) ;

if ( ! &CTCMMake( $line, $projname, $spec ) ) {
    print STDERR "Could not make '$line'\n" ;
}
