// Filename: classBuilder.cxx
// Created by:  drose (17Sep01)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) 2001, Disney Enterprises, Inc.  All rights reserved
//
// All use of this software is subject to the terms of the Panda 3d
// Software license.  You should have received a copy of this license
// along with this source code; you will also find a current copy of
// the license at http://www.panda3d.org/license.txt .
//
// To contact the maintainers of this program write to
// panda3d@yahoogroups.com .
//
////////////////////////////////////////////////////////////////////

#include "classBuilder.h"
#include "interrogate.h"


////////////////////////////////////////////////////////////////////
//     Function: ClassBuilder::Constructor
//       Access: Public
//  Description:
////////////////////////////////////////////////////////////////////
ClassBuilder::
ClassBuilder() {
  _struct_type = (CPPStructType *)NULL;
  _type_index = -1;
}

////////////////////////////////////////////////////////////////////
//     Function: ClassBuilder::Destructor
//       Access: Public, Virtual
//  Description:
////////////////////////////////////////////////////////////////////
ClassBuilder::
~ClassBuilder() {
}

////////////////////////////////////////////////////////////////////
//     Function: ClassBuilder::set_class
//       Access: Public, Virtual
//  Description: Sets the class that will be generated by this
//               ClassBuilder.  Returns true on success, false if the
//               class cannot be output for some reason.
////////////////////////////////////////////////////////////////////
bool ClassBuilder::
set_class(TypeIndex type_index, CPPStructType *struct_type) {
  _type_index = type_index;
  _struct_type = struct_type;
  return true;
}
