
#include "interrogate.cxx"
#include "typeManager.cxx"
#include "parameterRemap.cxx"
#include "parameterRemapBasicStringPtrToString.cxx"
#include "parameterRemapBasicStringRefToString.cxx"
#include "parameterRemapBasicStringToString.cxx"
#include "parameterRemapCharStarToString.cxx"
#include "parameterRemapConcreteToPointer.cxx"
#include "parameterRemapConstToNonConst.cxx"
#include "parameterRemapEnumToInt.cxx"
#include "parameterRemapPTToPointer.cxx"
#include "parameterRemapReferenceToConcrete.cxx"
#include "parameterRemapReferenceToPointer.cxx"
#include "parameterRemapThis.cxx"
#include "parameterRemapToString.cxx"
#include "parameterRemapUnchanged.cxx"

