import base64

from panda3d import core


def test_bam_rejects_truncated_endian_reversed_vertex_array_data():
    # Regression test for #1833.
    data = base64.b64decode(
        b"cGJqAAoNBgAAAAYALAAAAcUAAAAAjgAJAE0rZClsJ28ldAEvAAkATR1kG2wZbxdlATQACQBQD24N"
        b"YQtvCWUCBgAbAFQbcHRldHJhaGVkcm9uLmVnZwIAAwAEAAAAAAD/////AAAAAAAAAAAAAAABAAUA"
        b"AOr/AAAAAAAAWgAAAAKfAAsAUmVuZGVyU3RhdGUBrgAYAE5vZGVDYWNoZWRSZWZlcmVuY2VDb3Vu"
        b"dAE3ACEAQ2FjaGVkVHlwZWRXcml0YWJsZVJlZmVyZW5jZUNvdW50ATMAAgAAABwAAAACrgAOAFRy"
        b"YW5zZm9ybVN0YXRlAZ4AAwAFAAEAGQAAAAKcAA0AUmVuZGVyRWZmZWN0cwEzAAQAAABEAAAAAn8A"
        b"CABHZQEATm9kZQE0AAUACwBUZXRyYWhlZHJvbgIABgAEAAAAAAD/////AAAQAAAAAAAAAgABAAAA"
        b"AAABAAcAAgBJAAAAAq4AAAAQAAAASPlRP+QAAAAAAAAAAAAAAAAAAABI+VFAAAAAAAAAAAAAAAAA"
        b"AAAAAEj5UUAAAAAAAAAAAAAAAAAAAAAAAACAPy8AAAACUgEEAEdlb20BOAARAENvcHlPbldyaXRl"
        b"T2JqZWN0ATcABwAIAAEACQABAAAAADIAAAACawEOAEdlb21WZXN0ZXhEYXQOAEdlb21WZXJ0ZXhE"
        b"YXRhAThuCgADAQALAAAAAAAAADwAAAACYQENAEdlb21UcmlhbmdsZXMCWQENAEdlb21QcmltaXRp"
        b"dmUBOAAJAAAAAAAADAAAAAEDAAAAAAAAAAAiAAAAAnEBEABHZW9tVmVydGV4Rm9ybWF0ATMACgAA"
        b"AAAAAQAMAKQBAAACZwETAEdlb21WZXJ0ZXhBcnJheURhdGEBOAALAAwAA4ABAAAAAAAAJQZRv33Q"
        b"E78AAAAAYgdRvynLEz8AAAC/AAAAACUGUT8AAAAAfdATPwAAAABiB1G/KcsTPwAAAD8AAAC/JQZR"
        b"vwAAAAB90BM/AAAAAGIHUb8pyxM/AAAAPwAAAOoAAAAAJQZRP33QE78AAAAAYgdQPym9Ez8AAAC/"
        b"AAAAgCUGUb8AAAAAfdATPwAAAABiB1E/KcsTPwAAAD8AAAA/JQZRPwAAAAB90BM/AAAAAGIHUT8p"
        b"0hM/AAAAPwAAAL9NAAAAJQZGv33QE79iB1G/AAAAACnLE78AAAA/AAAAvyUGUb8AAAAAfdATP2IH"
        b"Ub8AAAAAKcsTvwAAAAAAAAA/AAAAACUGUT990BO/YfhRvwAAAAApyxO/AAAAvwAAAL8lBlE/AAAA"
        b"AH3QEz9iB1E/AAAAACnLE78AAAAAAAAAPwAAAAAlBlG/fdATv2IHUT8AAAAAKcsTvwAAAD8AAAC/"
        b"AAAAACUGUT990BO/YgdRPwAAAAApyxO/AAAAvwAAAL9AAAAAAmoBFQBHZW9tVmVydGV4QXJyYXlG"
        b"b3JtYXQBMwAMACAAIAAEAAADAA0AAwUBAAAEDgADBQkMAP0OAAIFBBgABB4AAAACcwEMAEludGVy"
        b"bmFsTmFtZQEzAA0ABgB2ZXJ0ZXgNAAAAAnMBDgAGAG5vcm1hbA8AAAACYQEPAAgAdGV4Y29vcmQB"
        b"AAAAAQ=="
    )

    stream = core.StringStream(data)
    bam_file = core.BamFile()
    assert bam_file.open_read(stream)
    try:
        bam_file.read_node(False)
    except Exception:
        return

    bam_file.resolve()
