#include "pnmImage.cxx"
#include "pnmImageHeader.cxx"
#include "pnmPainter.cxx"
#include "pnmReader.cxx"
#include "pnmReaderEmscripten.cxx"
#include "pnmWriter.cxx"
#include "pnmFileTypeRegistry.cxx"
#include "pnmimage_base.cxx" 
#include "ppmcmap.cxx"

