/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file dxOcclusionQueryContext9.I
 * @author drose
 * @date 2007-06-04
 */

/**
 *
 */
INLINE DXOcclusionQueryContext9::
DXOcclusionQueryContext9(IDirect3DQuery9 *query) : _query(query) {
}
