#include "config_android.cxx"
#include "jni_NativeIStream.cxx"
#include "jni_NativeOStream.cxx"
#include "pnmFileTypeAndroid.cxx"
#include "pnmFileTypeAndroidReader.cxx"
#include "pnmFileTypeAndroidWriter.cxx"
