// Filename: dataGraphTraversal.h
// Created by:  drose (26Jan99)
//
////////////////////////////////////////////////////////////////////

#ifndef DATAGRAPHTRAVERSAL_H
#define DATAGRAPHTRAVERSAL_H

////////////////////////////////////////////////////////////////////
//
// DataGraphTraversal
//
// This header file exists mainly to define the function
// traverse_data_graph(), which initiates a traversal of the data
// graph.
//
// This is the main interface to the data graph.  Traversing the data
// graph transmits data down the graph--reading data from devices and
// sending it to the DataNodes that want it.
////////////////////////////////////////////////////////////////////

#include <pandabase.h>

#include <traverserVisitor.h>
#include <allTransitionsWrapper.h>
#include <allAttributesWrapper.h>
#include <nullLevelState.h>


////////////////////////////////////////////////////////////////////
// 	 Class : DataGraphTraversal
// Description : This is mainly a holder for the static
//               _spam_flag_type TypeHandle, which is a registered
//               NumericDataAttribute that keeps track of the state of
//               the spam flag during data graph traversal.  The class
//               otherwise doesn't do anything useful, but see the
//               traverse_data_graph() function, below.
////////////////////////////////////////////////////////////////////
class EXPCL_PANDA DataGraphTraversal {
public:
  static void init_spam_flag();

  static TypeHandle _spam_flag_type;
};


////////////////////////////////////////////////////////////////////
// 	 Class : DataGraphVisitor
// Description : The TraverserVisitor to handle data graph traversals.
//               This manages the spam flag, and may eventually handle
//               merging of data from different parents into a single
//               node.
////////////////////////////////////////////////////////////////////
class EXPCL_PANDA DataGraphVisitor : 
  public TraverserVisitor<AllTransitionsWrapper, NullLevelState> {
public:
  bool reached_node(Node *node, AllAttributesWrapper &state, NullLevelState &);
};

 
////////////////////////////////////////////////////////////////////
//     Function: traverse_data_graph
//  Description: Initiates a traversal of the data graph given the
//               indicated root node, with no initial data.  Data
//               generated by the nodes encountered will be propagated
//               downwards.
////////////////////////////////////////////////////////////////////
void EXPCL_PANDA traverse_data_graph(Node *root);

#endif
