// Filename: dataGraphTraversal.cxx
// Created by:  drose (26Jan99)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) 2001, Disney Enterprises, Inc.  All rights reserved
//
// All use of this software is subject to the terms of the Panda 3d
// Software license.  You should have received a copy of this license
// along with this source code; you will also find a current copy of
// the license at http://www.panda3d.org/license.txt .
//
// To contact the maintainers of this program write to
// panda3d@yahoogroups.com .
//
////////////////////////////////////////////////////////////////////


#include "dataGraphTraversal.h"
#include "dataGraphTraverser.h"

#include <pStatTimer.h>
#include <pStatCollector.h>

#ifndef CPPPARSER
PStatCollector _dgraph_pcollector("App:Data graph");
#endif

////////////////////////////////////////////////////////////////////
//     Function: traverse_data_graph
//  Description: Initiates a traversal of the data graph given the
//               indicated root node, with no initial data.  Data
//               generated by the nodes encountered will be propagated
//               downwards.
////////////////////////////////////////////////////////////////////
void traverse_data_graph(Node *root) {
  PStatTimer timer(_dgraph_pcollector);
  {
    DataGraphTraverser dgt;
    dgt.traverse(root);
  }
}
