// Filename: dataGraphTraverser.h
// Created by:  drose (05Feb01)
// 
////////////////////////////////////////////////////////////////////

#ifndef DATAGRAPHTRAVERSER_H
#define DATAGRAPHTRAVERSER_H

#include <pandabase.h>

#include <nodeAttributes.h>

class Node;

////////////////////////////////////////////////////////////////////
// 	 Class : DataGraphTraverser
// Description : This class manages the traversal of the data graph,
//               so that all data attributes generated by nodes in the
//               graph are transmitted to nodes below them.
//
//               A bit of logic is employed to ensure that if a node
//               is assigned to two parents, the data from both
//               parents is merged before passing it to the child.
//
//               This class need not be exported from PANDA.DLL.
////////////////////////////////////////////////////////////////////
class DataGraphTraverser {
public:
  INLINE DataGraphTraverser();

  INLINE void traverse(Node *node);
  INLINE void traverse_below(Node *node, const NodeAttributes &data);

private:
  class SavedState {
  public:
    NodeAttributes _data;
    bool _has_spam_mode;
    int _num_parents_so_far;
  };

  void r_traverse(Node *node, NodeAttributes &data, bool has_spam_mode);
  void r_traverse_below(Node *node, NodeAttributes &data, bool has_spam_mode);
  void save(Node *node, const NodeAttributes &data, bool has_spam_mode,
	    int num_parents);
  void resume(Node *node, SavedState &state);
  void resume_all();

  typedef map<Node *, SavedState> States;
  States _saved_states;
};

#include "dataGraphTraverser.I"

#endif
