// Filename: dataGraphTraversal.cxx
// Created by:  drose (26Jan99)
// 
////////////////////////////////////////////////////////////////////

#include "dataGraphTraversal.h"
#include "dataGraphTraverser.h"
#include <pStatTimer.h>
#include <pStatCollector.h>

#ifndef CPPPARSER
PStatCollector _dgraph_pcollector("App:Data Graph", RGBColorf(0.5,0.8,0.4), 30);
#endif
  
////////////////////////////////////////////////////////////////////
//     Function: traverse_data_graph
//  Description: Initiates a traversal of the data graph given the
//               indicated root node, with no initial data.  Data
//               generated by the nodes encountered will be propagated
//               downwards.
////////////////////////////////////////////////////////////////////
void traverse_data_graph(Node *root) {
  PStatTimer timer(_dgraph_pcollector);
  {
    DataGraphTraverser dgt;
    dgt.traverse(root);
  }
}
