// Filename: dataGraphTraversal.h
// Created by:  drose (26Jan99)
//
////////////////////////////////////////////////////////////////////

#ifndef DATAGRAPHTRAVERSAL_H
#define DATAGRAPHTRAVERSAL_H

////////////////////////////////////////////////////////////////////
//
// DataGraphTraversal
//
// This header file exists mainly to define the function
// traverse_data_graph(), which initiates a traversal of the data
// graph.
//
// This is the main interface to the data graph.  Traversing the data
// graph transmits data down the graph--reading data from devices and
// sending it to the DataNodes that want it.
//
////////////////////////////////////////////////////////////////////

#include <pandabase.h>

class Node;
 
////////////////////////////////////////////////////////////////////
//     Function: traverse_data_graph
//  Description: Initiates a traversal of the data graph given the
//               indicated root node, with no initial data.  Data
//               generated by the nodes encountered will be propagated
//               downwards.
////////////////////////////////////////////////////////////////////
void EXPCL_PANDA traverse_data_graph(Node *root);

#endif
