#include "auto_bind.cxx"
#include "animBundle.cxx"
#include "animBundleNode.cxx"
#include "animChannel.cxx"
#include "animChannelBase.cxx"
#include "animChannelMatrixDynamic.cxx"
#include "animChannelMatrixFixed.cxx"
#include "animChannelMatrixXfmTable.cxx"
#include "animChannelScalarDynamic.cxx"
#include "animChannelScalarTable.cxx"
#include "animControl.cxx"
#include "animControlCollection.cxx"
#include "animGroup.cxx"

